= Увод в Perl 6
:description: Общо въведение в Perl 6
:Author: Naoum Hankache <naoum@hankache.com>; Красимир Беров <berov@cpan.org>
:keywords: perl6, perl 6, въведение, perl6intro, въведение в perl 6, урок по пърл 6, увод в perl 6
:Revision: 1.0
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:toc-title: Съдържание
:doctype: book
:lang: bg


Предназначението на това писание е да ви въведе набързо в езика за програмиране Perl 6. 
То ще ви даде начален тласък в използването и изучаването му. 

В някои от разделите ще намерите препратки към други по-пълни и точни части от
http://docs.perl6.org[документацията на Perl 6].  Така ще можете да четете
направо от източника, в случай че се нуждаете от повече информация по
определена тема.

В този урок ше намерите примери по най-обсъжданите теми.
За да ги разберете по-добре отделяйте време да правите примерите.

.Лиценз
Тази работа е лицензирана под "Признание - Споделяне на Споделеното 4.0 Международен Лиценз".
За да видите лиценза, посетете

* https://creativecommons.org/licenses/by-sa/4.0/.

.Принос
Ако желаете да допринесте за подобряването на това писание, отидете на

* https://github.com/hankache/perl6intro

.Отзиви
Всякакви отзиви са добре дошли:
* naoum@hankache.com
* berov@cpan.org

Ако тази работа ви харесва, отбележете хранилището със звезда на следния адрес:
link:https://github.com/hankache/perl6intro[Github].

.Преводи

* Български: http://bg.perl6intro.com
* Испански: http://es.perl6intro.com
* Немски: http://de.perl6intro.com
* Португалски: http://pt.perl6intro.com
* Френски: http://fr.perl6intro.com
* Японски: http://ja.perl6intro.com

:sectnums:
== Увод
=== Какво е Perl 6
Perl 6 е език от високо ниво, с общо предназначение и постепенна типизация на променливите.
Perl 6 е много-парадигмен. Той поддържа процедурно, обектно-ориентирано и функционално програмиране.

.Девизи на Perl 6:
* ИННН Има няколко начина да се направи. TMTOWTDI (Произнася се Tim Toady):
There is more than one way to do it.
* Лесните неща трябва да са лесни, трудните да стават по-лесни, а невъзможните - трудни.

=== Понятия
* *Perl 6*: Това е спецификация за език за програмиране с набор от тестове.
Реализации, които изпълняват тестовете без грешка, могат да се нарекат Perl 6.
* *Rakudo*: Е компилатор за Пърл 6.
* *Rakudobrew*: Е програма за управление инсталациите на Ракудо.
* *Panda*: Е инсталатор на модули за Пърл 6.
* *Rakudo Star*: Е вързоп: Ракудо, Панда, набор от модули за Пърл Perl 6, и документация.

=== Инсталиране на Пърл 6
.Линукс
. Инсталирайте Ракудобрю: https://github.com/tadzik/rakudobrew

. Инсталирайте Ракудо: Изпълнете следната команда в терминал `rakudobrew build moar`

. Инсталирайте Панда: Изпълнете следната команда в терминал `rakudobrew build panda`

.OSX
Имате четири възмоности:

* Следвайте същите стъпки като в Линукс
* Инсталирайте с хоумбрю: `brew install rakudo-star`
* Инсталирайте с МакПортс: `sudo port install rakudo`
* Свалете най-новият инсталатор (файл с разширение .dmg) от http://rakudo.org/downloads/star/

.Windows
. Свалете най-новия инсталатор (файл с разширение .msi) от
http://rakudo.org/downloads/star/ Ако архитектурата на системата ви е
32-битова, свалете файла с x86 в името; ако е 64-битова, свалете файла съдържащ
x86_64 в името.
. След инсталацията се уверете, че `C:\rakudo\bin` се намира в системната
променлива PATH

.Docker
. Вземете официалната картина за Docker `docker pull rakudo-star`
. След това стартирайте контейнер с картината `docker run -it rakudo-star`

=== Изпълнение на код, написан на Perl 6

Можете да изпълнявате код на Пърл 6 като използвате директно неговата
интерактивна конзола - REPL (Read-Eval-Print Loop). За да направите това,
отворете терминал, напишете `perl6` в терминала и натиснете [Enter]. Това ще
отвори конзолата и в нея ще се появи `>`.  След това напише някакъв програмен
код и натиснете [Enter]. На следващия ред в конзолата ще се появи резултатът от
изпълнението на кода.  Въведете друг ред, съдържащ програмен код или въведете
`exit` и натиснете [Enter], за да напуснете конзолата (REPL).

Друг начин за изпълнение е като въведете програмния код във файл, запишете го и
го изпълните. Препоръчва се за разширение на скриптовете, написани на Пърл 6 да
се използва `.pl6`. Изпълнете файла като напишете в терминал `perl6
filename.pl6` и натиснете  [Enter]. За разлика от интерактивната конзола
(REPL), всеки ред код ще се изпълни последователно но резултатът не ще се
изпише на екрана автоматично. Кодът трябва да съдържа израз, използващ командата
`say`, за да изведе нещо на стандартния изход (екрана).

Интерактивната конзола се използва най-вече за пробване на специфични парченца
код, обикновено едноредови изрази. За програми, състоящи се от повече редове, се
препоръчва да се записват във файл и след това да се изпълняват.

Едноредови изрази могат да се изпробват и на командния ред без интерактиванта
конзола като напишете `perl6 -e 'your code here'` и натиснете [Enter].

[TIP]
--
Rakudo Star върви с едноредов редактор, който се използва в интерактивната конзола (REPL).

Ако сте инсталирали обикновен Rakudo вместо Rakudo Star, най-вероятно
интерактивната конзола не ви дава възможност да редактирате текущия ред, да
ползвате стрелка нагоре и надолу, за да извиквате предишни команди и
да ги променяте или да ползвате табулация (клавишът TAB) за допълване на
частично въведени низове. Изпълнете една от следните команда и сте готови.

* `panda install Linenoise` ще работи в Windows, Linux и OSX

* `panda install Readline` ако сте на линукс и предпочитате библиотеката _Readline_
--

=== Редактори
Тъй като през повечето време ще записваме програмите си във файлове, ни е нужен
приличен текстов редактор, който разпознава синтаксиса на Пърл 6.

Аз лично използвам и препоръчвам https://atom.io/[Atom]. Той е модерен редактор
и поддържа синтаксиса на Пърл 6.
https://atom.io/packages/language-perl6fe[Perl6-fe] е допълнителен пакет за
оцветяване на кода на Пърл 6 за Атом. Той произхожда от оригиналния пакет,
който идва с Атом, но съдържа много подобрения и поправени грешки.

Други членове на общността използват също http://www.vim.org/[Vim], https://www.gnu.org/software/emacs/[Emacs] или http://padre.perlide.org/[Padre].

По-новите версии на Vim идват по подразбиране с поддръжка на синтаксиса на Пърл
6. Emacs и Padre изискват инсталиране на допълнителни пакети.


=== Здравей, Свят!
Ще започнем с ритуала `hello world`.

[source,perl6]
say 'Здравей, Свят!';

Това може да бъде написано и така:

[source,perl6]
'Здравей, Свят!'.say;

=== Преглед на синтаксиса
Пърл 6 е *свободна форма*: Свободни сте (през повечето време) да използвате
колкото ви е угодно празни пространства (за разлика от Питон - бел. прев.).

*Твърденията* са обикновено логически ред код. Те завършват с точка и запетая. +
`say "Здрасти" if True;`

*Изразите* са специален тип твърдение, което връща стойност:
`1+2` ще върне `3`

Изразите се състоят от *Членове* и *Оператори*.

*Членове*. Те са:

* *Променливи*: Съдържат стойност, която може да бъде променяна.

* *Буквални стойности (литерали)*: Непроменяема, буквална стойност - число или низ.

*Оператори*. Те са няколко типа:

|===

| *Тип* | *Обяснение* | *Пример*

| Представка | Преди члена. | `++1`

| Вставка | Между членовете | `1+2`

| Наставка | След члена | `1++`

| Ограждащ | Около члена | `(1)`

| Ограждаща наставка | След един член и ограждащ друг член | `Array[1]`

|===

==== Идентификатори (Имена)
Идентификаторите представляват имена, дадени на членовете.

.Правила:
* Трябва да започват с буква или знак за подчертавка.

* Могат да съдържат числа (ако не са първия знак в името на променливата).

* Могат да съдържат тирета или апострофи (ако не са първи или последен знак).
От дясната страна на тирето или апострофа винаги трябва да има буква.

|===

| *Правилно* | *Неправилно*

| `var1` | `1var`

| `var-one` | `var-1`

| `var'one` | `var'1`

| `var1_` | `var1'`

| `_var` | `-var`

|===

.Честo използвани начини за именуване (конвенции):
* КамилоОбразно: `variableNo1`

* шиш-кебап: `variable-no1`

* змие_видно: `variable_no1`

Можете да именувате променливите си както искате, но е добра практика да се
спрете на един вариант и да го следвате.

Като използвате смислени имена, ще улесните живота на всички, вашият и на вашите колеги.

* `var1 = var2 * var3` е правилно синтактично, но безсмислено.
* `monthly-salary = daily-rate * working-days` тези са по-смислени имена за променливи.

==== Коментари
Коментарът е текст, който компилаторът подминава и се ползва като бележка или пояснение.

Коментарите са три типа:

* Едноредови:
+
[source,perl6]
# Това е едноредов коментар

* Вложен/вмъкнат:
+
[source,perl6]
say #`(Това е вмъкнат коментар) "Hello World."

* Многоредови:
+
[source,perl6]
-----------------------------
=begin comment
Това е многоредов коментар.
Първа бележка
Второ пояснение
=end comment
-----------------------------

==== Кавички
Низовете се ограждат с двойни или единични кавички.

Използвайте двойни кавички, когато:

* низът ви съдържа апостроф;

* низът ви съдържа променливи.

[source,perl6]
-----------------------------------
say 'Hello World';   # Hello World
say "Hello World";   # Hello World
say "Don't";         # Don't
my $name = 'John Doe';
say 'Hello $name';   # Hello $name
say "Hello $name";   # Hello John Doe
-----------------------------------

== Оператори

=== Често използвани оператори
Следващата таблица изрежда най-често използваните оператори.
[cols="^.^5m,^.^5m,.^20,.^20m,.^20m", options="header"]
|===

| Оператор | Тип | Описание | Пример | Резултат

| + | Вставка | Събиране | 1 + 2 | 3

| - | Вставка | Изваждане | 3 - 1 | 2

| * | Вставка | Умножение | 3 * 2 | 6

| ** | Вставка | Степенуване | 3 ** 2 | 9

| / | Вставка | Деление | 3 / 2 | 1.5

| div | Вставка | Деление на цели числа (закръгля надолу) | 3 div 2 | 1

| % | Вставка | Деление до остатък | 7 % 4 | 3

.2+| %% .2+| Вставка .2+| Делимост | 6 %% 4 | False

<| 6 %% 3 <| True

| gcd | Вставка | Най-голям общ знаменател | 6 gcd 9 | 3

| lcm | Вставка | Най-малко общо кратно | 6 lcm 9 | 18

| == | Вставка | Цифрово равенство | 9 == 7  | False

| != | Вставка | Цифрово неравенство | 9 != 7  | True

| < | Вставка | По-малко | 9 < 7  | False

| > | Вставка | По-голямо | 9 > 7  | True

| \<= | Вставка | По-малко или равно | 7 \<= 7  | True

| >= | Вставка | По-голямо или равно | 9 >= 7  | True

| eq | Вставка | Еднаквост между низове | "John" eq "John"  | True

| ne | Вставка | Низовете не са еднакви | "John" ne "Jane"  | True

| = | Вставка | Присвояване | my $var = 7  | Присвояване на стойността `7` на променливата `$var`

.2+| ~ .2+| Вставка .2+| Свързване на низове | 9 ~ 7 | 97

<m| "Ей, " ~ "здрасти"  <| Ей, здрасти

.2+| x .2+| Вставка .2+| Повторение на низове | 13 x 3  | 131313

<| "Здрасти " x 3  <| Здрасти Здрасти Здрасти 

.5+| ~~ .5+| Вставка .5+| Умно съвпадение | 2 ~~ 2  | True

<| 2 ~~ Int <| True

<| "Perl 6" ~~ "Perl 6" <| True

<| "Perl 6" ~~ Str <| True

<| "enlightenment" ~~ /light/ <| ｢light｣

.2+| ++ | Представка | Увеличаване | my $var = 2; ++$var;  | Увеличава стойността на променливата с 1 и връща резулата `3`

<m| Наставка <d| Увеличаване <m| my $var = 2; $var++;  <| Връща стойността на променливата `2` и след това я увеличава с 1

.2+|\--| Представка | Намаляване | my $var = 2; --$var;  | Намалява стойността на променливата с 1 и връща резултата `1`

<m| Наставка <d| Намаляване <m| my $var = 2; $var--;  <| Връща стойността на променливата `2` и след това я намалява

.3+| + .3+| Prefix .3+| Свежда операнда до числова стойност | +"3"  | 3

<| +True <| 1

<| +False <| 0

.3+| - .3+| Представка .3+| Свежда операнда до числова стойност и връща отрицанието | -"3"  | -3

<| -True <| -1

<| -False <| 0

.6+| ? .6+| Prefix .6+| Свежда операнда до булева стойност | ?0 | False

<| ?9.8 <| True

<| ?"Hello" <| True

<| ?"" <| False

<| my $var; ?$var; <| False

<| my $var = 7; ?$var; <| True

| ! | Prefix | Свежда операнда до булева стойност и връща отрицанието | !4 | False

| .. | Вставка | Създател на поредица |  0..5  | Създава поредица от 0 до 5

| ..^ | Вставка | Създател на поредица |  0..^5  | Създава поредица от 0 до 4

| ^.. | Вставка | Създател на поредица |  0^..5  | Създава поредица от 1 до 5

| \^..^ | Вставка |  Създател на поредица |  0\^..^5  | Създава поредица от 1 до 4

| ^ | Представка | Създател на поредица |  ^5  | Също като 0..^5 Създава поредица от 0 до 4

| ... | Вставка | Мързелив създател на списък |  0...9999  |  return the elements only if requested

.2+| {vbar} .2+| Представка .2+| Сплескване | {vbar}(0..5)  | (0 1 2 3 4 5)

<| {vbar}(0\^..^5)  <| (1 2 3 4)

|===

=== Обърнати Оператори

Добавяне на `R` преди който и да е оператор, ще обърне операндите му.

[cols=".^m,.^m,.^m,.^m", options="header"]
|===
| Нормална операция | Резултат | Обърнат Оператор | Резултат

| 2 / 3 | 0.666667 | 2 R/ 3 | 1.5

| 2 - 1 | 1 | 2 R- 1 | -1

|===

=== Съкращаващи Оператори

Операторите за съкращения се прилагат върху списък от стойности.
Съставят се като операторът се огради със `[]`

[cols=".^m,.^m,.^m,.^m", options="header"]
|===
| Нормална операция | Резултат | Съкращаващ оператор | Резултат

| 1 + 2 + 3 + 4 + 5 | 15 | [+] 1,2,3,4,5 | 15

| 1 * 2 * 3 * 4 * 5 | 120 | [*] 1,2,3,4,5 | 120

|===

NOTE:  За да видите пълния списък с оператори и приоритетите им, отидете на
https://docs.perl6.org/language/operators

== Променливи
Променливите в Пърл 6 биват три типа - Скалари, Масиви и Хешове.

Променливите се различават по т.нар *сиджил* (означава "знак" на латински). Този
знак се намира в началото на всяка променлива.

* `$` се използва за скалари
* `@` се използва за масиви
* `%` се използва за хешове

=== Скалари 
Скаларът (Scalar) съдържа единична стойност или указател (reference).
[NOTE]
====
Бел. прев.:
Указателите в Пърл не са като указателите в C и затова са познати
повече като референции. Все пак по-подходящата дума е указател, а не
референция.
====

[source,perl6]
----
#Низ (String)
my $name = 'Перко Наумов';
say $name;

#Цяло число (Integer)
my $age = 99;
say $age;
----

В зависимост от стойността, която съдържа скаларната променлива (нейния тип),
върху нея могат да се извършват различни действия.

[source,perl6]
.Низ
----
my $name = 'Перко Наумов';
say $name.uc;
say $name.chars;
say $name.flip;
----

----
ПЕРКО НАУМОВ
12
вомуаН окреП
----

ВАЖНО: За да видите пълния списък с методите, приложими върху низове (скаларни
променливи от тип Str), вижте https://docs.perl6.org/type/Str

[source,perl6]
.Цяло число
----
my $age = 17;
say $age.is-prime;
----

----
True
----

ВАЖНО: За да видите пълния списък с методите, приложими върху цели числа
(скаларни променливи от тип Int), вижте https://docs.perl6.org/type/Int

[source,perl6]
.Рационално число
----
my $age = 2.3;
say $age.numerator;
say $age.denominator;
say $age.nude;
----

----
23
10
(23 10)
----

ВАЖНО: За да видите пълния списък с методите, приложими върху цели числа
(скаларни променливи от тип Rat), вижте https://docs.perl6.org/type/Rat

=== Масиви 
Масивите (Arrays) са списъци, които съдържат множество стойности.

[source,perl6]
----
my @animals = 'камила','лама','сова';
say @animals;
----

От долния пример се вижда, че върху масивите могат да се извършват много операции:

СЪВЕТ: Тилдата `~` се използва за свързване на низове.

[source,perl6]
.`Script`
----
my @animals = 'camel','vicuña','llama';
say "В зоологическата градина има " ~ @animals.elems ~ " животни.";
say "Животните са: " ~ @animals;
say "Аз ще осиновя една сова";
@animals.push("owl");
say "Сега в градината ми има: " ~ @animals;
say "The first animal we adopted was the " ~ @animals[0];
@animals.pop;
say "Unfortunately the owl got away and we're left with: " ~ @animals;
say "We're closing the zoo and keeping one animal only";
say "We're going to let go: " ~ @animals.splice(1,2) ~ " and keep the " ~ @animals;
----

.`Изход`
----
В зоологическата градина има 3 животни.
Животните са: camel vicuña llama
Аз ще осиновя една сова
Сега в градината ми има: camel vicuña llama owl
The first animal we adopted was the camel
Unfortunately the owl got away and we're left with: camel vicuña llama
We're closing the zoo and keeping one animal only
We're going to let go: vicuña llama and keep the camel
----

.Обяснение
`.elems` връща броя на елементите в масива. +
`.push()` добавя един или повече елементи към масива. +
Можем да достъпим отделен елемент от масива като укажем мястото му `@animals[0]`. +
`.pop` премахва последния елемент от масива и го връща. +
`.splice(a,b)` ще премахне `b` елемента като започне от позиция `a`.

==== Масиви с предопределен размер
Обикновено масив се обявява по следния начин:
[source,perl6]
my @array;

По подразбиране масивът има неопределен брой елементи и затова го наричат
автоматично-разширяващ се.  Масивът ще приеме какъвто и да е брой стойности без
ограничение.

Но можем да създаваме и масиви с определен брой елементи.  В такива масиви не
можете да достъпите или добавяте елементи извън определения размер на масива.

За да обявите масив с определен брой елементи, добавете броя на елементите в
квадратни скоби веднага след името на масива.
[source,perl6]
my @array[3];

Този масив ще може да съдържа най-много три стойности с места от 0 до 2.

[source,perl6]
----
my @array[3];
@array[0] = "първа стойност";
@array[1] = "втора стойност";
@array[2] = "трета стойност";
----

Не можете да добавите четвърта стойност в този масив:
[source,perl6]
----
my @array[3];
@array[0] = "първа стойност";
@array[1] = "втора стойност";
@array[2] = "трета стойност";
@array[3] = "четвърта стойност";
----

----
Index 3 for dimension 1 out of range (must be 0..2)
----

==== Многомерни масиви 
Масивите, които видяхме до тук са едномерни. За щастие можем да създаваме и
многомерни масиви в Пърл 6.

[source,perl6]
my @tbl[3;2];

Този масив е двумерен.
Първото измерение може да съдържа най-много 3 стойности, а второто - най-много 2.

Представете си го като таблица с 3 реда и 2 колони.

[source,perl6]
----
my @tbl[3;2];
@tbl[0;0] = 1;
@tbl[0;1] = "x";
@tbl[1;0] = 2;
@tbl[1;1] = "y";
@tbl[2;0] = 3;
@tbl[2;1] = "z";
say @tbl
----

----
[[1 x] [2 y] [3 z]]
----

.Нагледно представяне на масива:
----
[1 x]
[2 y]
[3 z]
----

ВАЖНО: За да видите пълния справочник за масив (Array), посетете
https://docs.perl6.org/type/Array

=== Хешове
[source,perl6]
.Хешът (Hash) е набор от двойки Ключ/Стойност.
----
my %столици = ('UK','London','Germany','Berlin');
say %столици;
----

[source,perl6]
.Ето и друг сбит начин за попълване на хеша:
----
my %capitals = (UK => 'London', Germany => 'Berlin');
say %capitals;
----

Някои от методите, които могат да се извикват върху хешове са:
[source,perl6]
.`Скрипт`
----
my %capitals = (UK => 'London', Germany => 'Berlin');
%capitals.push: (France => 'Paris');
say %capitals.kv;
say %capitals.keys;
say %capitals.values;
say "The capital of France is: " ~ %capitals<France>;
----

.`Изход`
----
(France Paris Germany Berlin UK London)
(France Germany UK)
(Paris Berlin London)
The capital of France is: Paris
----

.Обяснение
`.push: (key => 'Value')` добавя нова двойка ключ/стойност. +
`.kv` връща списък, съдържаш всички ключове и стойности. +
`.keys` връща списък, съдържаш всички ключове. +
`.values` връща списък, съдържаш всички стойности. +
Можем да достъпим отделна стойност в хеша като укажем нейния ключ `%hash<key>`

ВАЖНО: За да видите пълния справочник за хешовете, посетете https://docs.perl6.org/type/Hash

=== Типове
В примерите досега не задавахме типа стойност, който да съдържа променливата.

СЪВЕТ: `.WHAT` Ще върне типа на стойността, съдържаща се в променливата.

[source,perl6]
----
my $var = 'Text';
say $var;
say $var.WHAT;

$var = 123;
say $var;
say $var.WHAT;
----

Както виждате от горния пример, типа на стойността в променливата `$var` първо
беше (Str)  и след това (Int).

Този начин на програмиране се нарича динамично типизиране. Динамично означава,
че променливите могат да съдържат стойности от *Всякакъв* (Any) тип.

Сега опитайте да изпълните следния пример. Обърнете внимание на използването на
`Int` пред името на променливата.

[source,perl6]
----
my Int $var = 'Text';
say $var;
say $var.WHAT;
----

Присвояването ще се провали и ще върне следната грешка: +
 `Type check failed in assignment to $var; expected Int but got Str` +
 `Проверката за тип е неуспешна при присвояване на $var; очакваше се Int, но бе подаден Str`

Този път указахме, че типа на променливата ще бъде (Int).
Опитът да му присвоим низ (Str), не беше успешен.

Този начин на програмиране се нарича статично типизиране. Статично означава, че типа на променливите се указва предварително и не може да бъде променян.

Пърл 6 е *постепенно типизиран*; позволява *статично* и *динамично* типизиране.

.Масивите и хешовете могат също да бъдат статично типизирани:
[source,perl6]
----
my Int @array = 1,2,3;
say @array;
say @array.WHAT;

my Str @multilingual = "Здравей", "Hello","Salut","Hallo","您好","안녕하세요","こんにちは";
say @multilingual;
say @multilingual.WHAT;

my Str %capitals = (UK => 'London', Germany => 'Berlin');
say %capitals;
say %capitals.WHAT;

my Int %country-codes = (UK => 44, Germany => 49);
say %country-codes;
say %country-codes.WHAT;
----

.Ето спиаък с най-често използваните типове:
Най-вероятно никога няма да използвате първите два, но са упоменати, да ги знаете.

[cols="^.^1m,.^3m,.^2m,.^1m, options="header"]
|===

| *Тип* | *Описание* | *Пример* | *Резултат*

| Mu | Коренът на йерархията на типовете в Перл 6 | |

| Any | Подразбиращият се родителски клас за нови класове и за повечето стандартни класове | |

| Cool | Стойност, която може да бъде ползвана като низ и число едновременно | my Cool $var = 31; say $var.flip; say $var * 2; | 13 62

| Str | Низ от знакове | my Str $var = "NEON"; say $var.flip; | NOEN

| Int | Цяло число (случайна точност) | 7 + 7 | 14

| Rat | Рационално число (ограничена точност) | 0.1 + 0.2 | 0.3

| Bool | Булева стойност (Истина или Лъжа) | !True | False

|===

=== Самонаблюдение

Самонаблюдение (Introspection) е действието по взимане на информация за даден обект, например какъв е типът му. +
В един от предишните примери използвахме `.WHAT`, за да върнем типа на променливата.

[source,perl6]
----
my Int $var;
say $var.WHAT;    # (Int)
my $var2;
say $var2.WHAT;   # (Any)
$var2 = 1;
say $var2.WHAT;   # (Int)
$var2 = "Hello";
say $var2.WHAT;   # (Str)
$var2 = True;
say $var2.WHAT;   # (Bool)
$var2 = Nil;
say $var2.WHAT;   # (Any)
----

Типът на дадена променлива показва каква стойност може да съдържа. +
Типът на *силно* обявена празна променлива е типа, с който е била обявена. +
Типът на празна променлива, която не е силно обявена е *Всякакъв* `(Any)` +
За да изчистите стойността на променлива, присвойте и `Nil`.

=== Видимост
Преди да използвате променлива за първи път, трябва да я обявите.

В Пърл 6 се използват няколко начина за обявяване на променливи. В примерите
досега използвахме `my`.

[source,perl6]
my $var=1;

Операторът `my` дава на променливата *словна* (*lexical*) видимост.
Иначе казано, променливата ще бъде видима (използваема) само в блока от код, в който е обявена.

В Пърл 6 блокът представлява всичко намиращо се между двойка отваряща и затваряща фигурни скоби - `{ }`.
Ако няма определен блок, променливата е достъпна в целия скрипт.

[source,perl6]
----
{
  my Str $var = 'Text';
  say $var; #is accessible
}
say $var; # е недостъпна, връща грешка
----

Тъй като променливата е видима само в блока, в който е обявена, можете да
ползвате същото име за друга променлива в друг блок.

[source,perl6]
----
{
  my Str $var = 'Text';
  say $var;
}
my Int $var = 123;
say $var;
----

=== Присвояване и Обвързване
В предишните примери видяхме как да *присвояваме* стойности на променливи. +
*Присвояването* се прави с помощта на оператора `=`.
[source,perl6]
----
my Int $var = 123;
say $var;
----

Можем да променим стойността присвоена на променлива:

[source,perl6]
.Присвояване
----
my Int $var = 123;
say $var;
$var = 999;
say $var;
----

.`Изход`
----
123
999
----

Когато *обвързваме* стойност с променлива - напротив. Не можем да променим стойността. +
*Обвързването* се извършва с помощта на оператора `:=`.

[source,perl6]
.Обвързване
----
my Int $var := 123;
say $var;
$var = 999;
say $var;
----

.`Изход`
----
123
Cannot assign to an immutable value
----

[source,perl6]
.Променливите могат да бъдат обвързвани и с други променливи:
----
my $a;
my $b;
$b := $a;
$a = 7;
say $b;
$b = 8;
say $a;
----

.`Изход`
----
7
8
----

Обвързването на променливи една с друга, както забелязахте, е двупосочно. +
Резултатът от `$a := $b` и `$b := $a` е един и същ.

ВАЖНО: Повече за променливите ще научите на адрес https://docs.perl6.org/language/variables

