= Perl 6 Introduction
:description: Une introduction generale a Perl 6
:Author: Naoum Hankache
:keywords: perl6, perl 6, introduction, perl6intro, perl 6 introduction
:Email: naoum@hankache.com
:Revision: 1.0
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left

L'objectif de ce document est de vous donner un aperçu rapide du langage de programmation Perl 6. +
Pour ceux qui sont nouveaux à Perl 6, il devrait vous permettre de démarrer.

Certaines sections de ce document référencent d'autres parties (plus complètes et précises) de la documentation de Perl 6.
Vous devriez les lire si vous avez besoin de plus d'information sur un sujet précis.

En lisant ce document, vous trouverez des exemples pour la plus part des sujets discutés.
Pour mieux les comprendre, vous pouvez expérimenter en les modifiant.

.Licence
Ce document est sous licence Creative Commons Attribution -  Partage dans les Mêmes Conditions 4.0 International. +
Pour accéder à une copie de cette licence, merci de vous rendre à l'adresse suivante http://creativecommons.org/licenses/by-sa/4.0/.

.Contribution
Si vous souhaitez contribuer à ce document rendez-vous à l'adresse suivante: +
http://github.com/hankache/perl6intro

:sectnums:
== Introduction
=== Perl 6 c'est quoi?
Perl 6 est un langage générique supportant un typage graduel.
Perl 6 supporte plusieurs paradigmes dont, la Programmation Procédurale, Orientée Objet et Fonctionelle.

.Perl 6 motto:
* TMTOWTDI (Prononcé Tim Toady): There is more than one way to do it: +
Il y a plus d'une façon de le faire.
* Easy things should stay easy, hard things should get easier, and impossible things should get hard: +
Les choses faciles doivent rester faciles, les choses dures devraient devenir plus faciles, et les choses impossibles devraient devenir dures.

=== Jargon
Perl 6 est une spécification de langage avec une suite de tests. Les implémentations qui passent la suite de tests sont considérées comme Perl 6. +
Rakudo est un compilateur pour Perl 6. +
Rakudobrew est un gestionnaire d'installation pour Perl 6. +
Panda est un installateur de modules pour Perl 6.

=== Installer Perl 6
.Linux
. Installer Rakudobrew: https://github.com/tadzik/rakudobrew

. Installer Rakudo: Tapez la commande suivante dans le terminal `rakudobrew build moar`

. Installer Panda: Tapez la commande suivante dans le terminal `rakudobrew build-panda`

.OSX
Suivez les mêmes étapes indiquées pour l'installation sur Linux +
ou +
Installer avec homebrew: `brew install rakudo-star`

.Windows
. Téléchargez l'installateur le plus récent (fichier avec une extension .MSI) de http://rakudo.org/downloads/star/ +
Si votre système possède une architecture 32-bit, téléchargez le fichier x86. S'il possède une architecture 64-bit téléchargez le fichier x86_64.
. Apres l'installation, ajouter C:\rakudo\bin a votre PATH

.Docker
. Obtenez l'image officielle `docker pull rakudo-star`
. Ensuite exécutez `docker run -it rakudo-star`

=== Exécuter Perl 6
Pour exécuter un code écrit en Perl 6 vous pouvez utiliser le REPL (Read-Eval-Print Loop). +
Dans votre terminal, tapez `perl6`, tapez votre code et pressez [Enter] +

Alternativement, vous pouvez écrire votre code dans un fichier, l'enregistrer et puis l'exécuter. +
Il est recommandé de créer les fichiers Perl 6 avec l'extension `.pl6`. +
Exécutez le fichier du terminal en utilisant cette syntaxe: `perl6 filename.pl6`

Le REPL est surtout utilisé pour essayer un morceau de code, typiquement une unique ligne de code. +
Pour les programmes contenant plusieurs lignes, il est recommandé de les stocker dans un fichier, puis de les exécuter.

=== Editeurs

Comme la plupart du temps, nous allons écrire et stocker nos programmes en Perl 6 dans des fichiers,
nous devrions avoir un éditeur de texte décent qui reconnaît la syntaxe de Perl 6.

Je recommande personnellement https://atom.io/[Atom]. C'est un éditeur de texte moderne livré avec une coloration syntaxique pour Perl 6.

D'autres personnes de la communauté utilisent aussi http://www.vim.org/[Vim], https://www.gnu.org/software/emacs/[Emacs] ou http://padre.perlide.org/[Padre].

Les versions récentes de Vim sont livrées avec la coloration syntaxique pour Perl 6. Emacs et Padre nécessiteront l'installation de paquets supplémentaires.


=== Hello World!
Nous allons commencer avec le rituel `hello world`.

[source,perl6]
say 'hello world';

=== Aperçu de la syntaxe
Perl 6 est en *forme libre*: Vous êtes libre (la plupart du temps) à utiliser n'importe quelle quantité d'espaces.

Les *Instructions* sont typiquement une ligne logique de code, un point-virgule est nécessaire à leur fin: +
`say "Hello" if True;`

Les *Expressions* sont un type spécial d'instructions qui retournent une valeur: +
`1+2` retourne `3`

Les expressions sont faites de *Termes* et d'*Operateurs*.

Les *Termes* sont des:

* *Variables*: Une valeur qui peut être manipulée ou changée.

* *Littérales*: Une valeur constante comme un nombre ou une chaîne.

Les *Opérateurs* sont classés en types:

|===

| *Type* | *Explication* | *Exemple*

| Préfixe | Avant le terme. | `++1`

| Infixe | Entre deux termes. | `1+2`

| Suffixe | Après le terme. | `1++`

| Circonfixe | Autour du terme. | `(1)`

| Postcirconfixe | Après un terme, autour d'un autre  | `Array[1]`

|===

==== Identificateurs
Les identificateurs sont le nom donné aux termes lors de leur définition.

.Règles:
* Ils doivent commencer par un caractère alphabétique ou un tiret bas (under score).

* Ils peuvent contenir des chiffres (à l'exception du premier caractère).

* Ils peuvent contenir des tirets ou des apostrophes (sauf le premier et le dernier caractère),
mais avec un caractère alphabétique sur le côté droit de chaque tiret / apostrophe.

|===

| *Valide* | *Non valide*

| `var1` | `1var`

| `var-one` | `var-1`

| `var'one` | `var'1`

| `var1_` | `var1'`

| `_var` | `-var`

|===

.Conventions de nommage:
* Camel: `variableNo1`

* Kebab: `variable-no1`

* Snake: `variable_no1`

Vous êtes libre de nommer vos identificateurs comme vous le souhaitez,
mais choisissez une convention de nommage et tenez-vous y.

L'utilisation de noms signifiants facilitera votre vie et celle des autres. +
`var1 = var2 * var3` est syntaxiquement correct mais son but n'est pas évident. +
`monthly-salary = daily-rate * working-days` serait une meilleure façon de nommer vos variables.

==== Commentaires
Un commentaire est du texte ignoré par le compilateur.

Il y a 3 types de commentaires:

* Ligne unique:
+
[source,perl6]
#Ceci est une seule ligne de commentaire

* Intégré:
+
[source,perl6]
say #`(Ceci est un commentaire intégré) "Hello World."

* Multi ligne:
+
[source,perl6]
-----------------------------
=begin comment
Ceci est un commentaire sur plusieurs lignes.
Commentaire 1
Commentaire 2
=end comment
-----------------------------

==== Guillemets
Les chaînes doivent être délimitées par des guillemets droits doubles ou simples.

Utilisez toujours des guillemets droits doubles:

* si votre chaîne contient une apostrophe.

* si votre chaîne contient une variable qui doit être interpolée.

[source,perl6]
-----------------------------------
say 'Hello World';               #Hello World
say "Hello World";               #Hello World
say "Quelqu'un m'a dit";         #Quelqu'un m'a dit
my $nom = 'Jean Dupont';
say 'Salut $name';               #Salut $nom
say "Salut $name";               #Salut Jean Dupont
-----------------------------------

== Operateurs
[cols="^.^5m,^.^5m,.^20,.^20m,.^20m", options="header"]
|===

| Operateur | Type | Description | Exemple | Résultat

| + | Infixe | Addition | 1 + 2 | 3

| - | Infixe | Soustraction | 3 - 1 | 2

| * | Infixe | Multiplication | 3 * 2 | 6

| ** | Infixe | Puissance | 3 ** 2 | 9

| / | Infixe | Division | 3 / 2 | 1.5

| div | Infixe | Division (arrondi) | 3 div 2 | 1

| % | Infixe | Reste | 7 % 4 | 3

.2+| %% .2+| Infixe .2+| Divisibilité | 6 %% 4 | False

<| 6 %% 3 <| True

| gcd | Infixe | Plus grand dénominateur commun | 6 gcd 9 | 3

| lcm | Infixe | Plus petit commun multiple | 6 lcm 9 | 18

| == | Infixe | Egalité | 9 == 7  | False

| != | Infixe | Inégalité | 9 != 7  | True

| < | Infixe | Plus petit | 9 < 7  | False

| > | Infixe | Plus grand | 9 > 7  | True

| \<= | Infixe | Plus petit ou égal | 7 \<= 7  | True

| >= | Infixe | Plus grand ou égal | 9 >= 7  | True

| eq | Infixe | Egalité (chaînes) | "John" eq "John"  | True

| ne | Infixe | Inégalité (chaînes) | "John" ne "Jane"  | True

| = | Infixe | Affectation | my $var = 7  | Attribue la valeur `7` a la variable `$var`

.2+| ~ .2+| Infixe .2+| Concaténation | 9 ~ 7 | 97

<m| "Hi " ~ "there"  <| Hi there

.2+| x .2+| Infixe .2+| Réplication | 13 x 3  | 131313

<| "Hello " x 3  <| Hello Hello Hello

| ~~ | Infixe | Smart match |   |

.2+| ++ | Préfixe | Incrémentation | my $var = 2; ++$var;  | Incrémente la variable de 1 et retourne le résultat `3`

<m| Suffixe <d| Incrémentation <m| my $var = 2; $var++;  <| Retourne la variable `2` et puis l'incrémente

.2+|\--| Préfixe | Décrémentation | my $var = 2; --$var;  | Décrémente la variable de 1 et retourne le résultat `1`

<m| Suffixe <d| Décrémentation <m| my $var = 2; $var--;  <| Retourne la variable `2` et puis la décrémente

.3+| + .3+| Préfixe .3+| Force l'opérande a une valeur numérique | +"3"  | 3

<| +True <| 1

<| +False <| 0

.3+| - .3+| Préfixe .3+| Force l'opérande a une valeur numérique et retourne la négation | -"3"  | -3

<| -True <| -1

<| -False <| 0

.6+| ? .6+| Préfixe .6+| Force l'opérande a une valeur booléenne | ?0 | False

<| ?9.8 <| True

<| ?"Hello" <| True

<| ?"" <| False

<| my $var; ?$var; <| False

<| my $var = 7; ?$var; <| True

| ! | Préfixe | Force l'opérande a une valeur booléenne et retourne la négation | !4 | False

| .. | Infixe | Construction de gammes |  0..5  | Crée une gamme de 0 a 5

| ..^ | Infixe | Construction de gammes |  0..^5  | Crée une gamme de 0 a 4

| ^.. | Infixe | Construction de gammes |  0^..5  | Crée une gamme de 1 a 5

| \^..^ | Infixe | Construction de gammes |  0\^..^5  | Crée une gamme de 1 a 4

| ^ | Préfixe | Construction de gammes |  ^5  | Comme 0..^5 Crée une gamme de 0 a 4

| ... | Infixe | Construction de listes paresseuses |  0...9999  |  Retourne les éléments seulement si nécessaire

.2+| {vbar} .2+| Préfixe .2+| Aplanissement | {vbar}(0..5)  | (0 1 2 3 4 5)

<| {vbar}(0\^..^5)  <| (1 2 3 4)

|===

NOTE: Pour la liste complète des opérateurs, y compris leur priorité: http://doc.perl6.org/language/operators

== Variables
Les variables sont classés en 3 catégories: Scalaires, Tableaux et Hachages.

Un *sigil* (Signe en Latin) est un caractère utilisé comme préfixe pour classer les variables.

* `$` est utilisé pour les scalaires
* `@` est utilisé pour les tableaux
* `%` est utilisé pour les tables de hachage.

=== Scalaires
Un scalaire tient une valeur ou une référence.

[source,perl6]
----
#Chaine
my $nom = 'Jean Dupont';
say $name;

#Entier
my $age = 99;
say $age;
----

=== Tableaux
Les tableaux sont des listes contenant plusieurs valeurs.

[source,perl6]
----
my @animaux = ['chameau','llama','hibou'];
say @animaux;
----

De nombreuses opérations peuvent être effectuées sur les tableaux comme démontré dans l'exemple suivant:

TIP: Le tilde `~` est utilisé pour la concaténation.

[source,perl6]
.`Script`
----
my @animaux = ['chameau','vicuña','llama'];
say "Le zoo contient " ~ @animaux.elems ~ " animaux";
say "Les animaux sont: " ~ @animaux;
say "Je vais adopter un hibou pour le zoo";
@animaux.push("hibou");
say "Maintenant, mon zoo contient: " ~ @animaux;
say "Le premier animal que nous avons adopté est le " ~ @animaux[0];
@animaux.pop;
say "Malheureusement, le hibou est parti, il ne nous reste que: " ~ @animaux;
say "Nous allons fermer le zoo et laisser un animal seulement";
say "Nous allons laisser partir: " ~ @animaux.splice(1,2) ~ " et laisser le " ~ @animaux;
----

.`Output`
----
Le zoo contient 3 animaux
Les animaux sont: chameau vicuña llama
Je vais adopter un hibou pour le zoo
Maintenant, mon zoo contient: chameau vicuña llama hibou
Le premier animal que nous avons adopté est le chameau
Malheureusement, le hibou est parti, il ne nous reste que: chameau vicuña llama
Nous allons fermer le zoo et laisser un animal seulement
Nous allons laisser partir: vicuña llama et laisser le chameau
----

.Explication
`.elems` retourne le nombre d'éléments contenus dans le tableau. +
`.push()` ajoute un élément au tableau. +
Nous pouvons accéder à un élément spécifique dans le tableau en spécifiant sa position `@animaux[0]`. +
`.pop` supprime le dernier élément du tableau. +
`.splice(a,b)` supprime les `b` éléments a partir de la position `a`.

NOTE: Pour la référence complète des tableaux: http://doc.perl6.org/type/Array

=== Hachage
Un hachage (table de hachage / hash) est un ensemble de paires clef / valeur.

[source,perl6]
----------------------------------------------------
my %capitales = ('Londres','Angleterre','Paris','France');
say %capitales;

#une autre façon succincte de remplir le hachage:
my %capitales = (Londres => 'Angleterre', Paris => 'France');
say %capitales;
----------------------------------------------------

=== Types
Dans les exemples précédents, on n'a pas précisé quel type de valeurs les variables peuvent tenir.

TIP: `.WHAT` retournera le type de la valeur contenue dans la variable.

[source,perl6]
---------------------
my $var = 'Text';
say $var;
say $var.WHAT;

$var = 123;
say $var;
say $var.WHAT;
---------------------

Comme vous pouvez le voir dans l'exemple ci-dessus, le type de valeur contenu dans `$var` était (Str) et puis (Int).

Ce style de programmation est appelé le typage dynamique.
Dynamique dans le sens que les variables peuvent contenir des valeurs de tout type.

Maintenant, essayez d'exécuter l'exemple ci-dessous: +
Remarquez `Int` avant le nom de la variable.

[source,perl6]
-----------------------------------------
my Int $var = 'Text';
say $var;
say $var.WHAT;
-----------------------------------------

Il va échouer et retourner ce message d'erreur: `Type check failed in assignment to $var; expected Int but got Str`

Ce qui est arrivé est que nous avons précisé au préalable que la variable doit être de type (Int).
Quand nous avons essayé de lui affecter un (Str), le programme a échoué.

Ce style de programmation est appelé le typage statique. Statique dans le sens que les types de variables sont définies avant l'affectation et ne peuvent pas changer.

Perl 6 possède un *typage graduel*; les deux typages *statique* et *dynamique* peuvent être utilisés.

Voici une liste des types les plus couramment utilisés. +
Les deux premiers ne seront probablement jamais utilisés, mais ils sont répertoriés à titre informatif.

[cols="^.^1m,.^3m,.^2m,.^1m, options="header"]
|===

| *Type* | *Description* | *Exemple* | *Résultat*

| Mu | La racine de la hiérarchie de types | |

| Any | Classe de base par défaut pour les nouvelles classes et pour la plupart des classes intégrées | |

| Cool | Valeur qui peut être considérée comme une chaîne ou un nombre interchangeable | my Cool $var = 31; say $var.flip; say $var * 2; | 13 62

| Str | Chaîne de caractères | my Str $var = "NEON"; say $var.flip; | NOEN

| Int | Entier (précision arbitraire) | 7 + 7 | 14

| Rat | Nombre rationnel (précision limitée) | 0.1 + 0.2 | 0.3

| Bool | Booléen | !True | False

|===
