= Introduction à Perl 6
:description: Une introduction générale à Perl 6
:Author: Naoum Hankache
:keywords: perl6, perl 6, introduction, perl6intro, perl 6 introduction, Introduction à Perl 6
:Email: naoum@hankache.com
:Revision: 1.0
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:toc-title: Table des matières

L'objectif de ce document est de vous donner un aperçu rapide du langage de programmation Perl 6. +
Pour ceux qui sont nouveaux à Perl 6, il devrait vous permettre de démarrer.

Certaines sections de ce document référencent d'autres parties (plus complètes et précises) de la documentation de Perl 6.
Vous devriez les lire si vous avez besoin de plus d'information sur un sujet précis.

En lisant ce document, vous trouverez des exemples pour la plus part des sujets discutés.
Pour mieux les comprendre, vous pouvez expérimenter en les modifiant.

.Licence
Ce document est sous licence Creative Commons Attribution -  Partage dans les Mêmes Conditions 4.0 International. +
Pour accéder à une copie de cette licence, merci de vous rendre à l'adresse suivante http://creativecommons.org/licenses/by-sa/4.0/.

.Contribution
Si vous souhaitez contribuer à ce document rendez-vous à l'adresse suivante: +
http://github.com/hankache/perl6intro

:sectnums:
== Introduction
=== Perl 6 c'est quoi?
Perl 6 est un langage générique supportant un typage graduel.
Perl 6 supporte plusieurs paradigmes dont, la Programmation Procédurale, Orientée Objet et Fonctionelle.

.Perl 6 motto:
* TMTOWTDI (Prononcé Tim Toady): There is more than one way to do it: +
Il y a plus d'une façon de le faire.
* Easy things should stay easy, hard things should get easier, and impossible things should get hard: +
Les choses faciles doivent rester faciles, les choses dures devraient devenir plus faciles, et les choses impossibles devraient devenir dures.

=== Jargon
Perl 6 est une spécification de langage avec une suite de tests. Les implémentations qui passent la suite de tests sont considérées comme Perl 6. +
Rakudo est un compilateur pour Perl 6. +
Rakudobrew est un gestionnaire d'installation pour Perl 6. +
Panda est un installateur de modules pour Perl 6.

=== Installer Perl 6
.Linux
. Installer Rakudobrew: https://github.com/tadzik/rakudobrew

. Installer Rakudo: Tapez la commande suivante dans le terminal `rakudobrew build moar`

. Installer Panda: Tapez la commande suivante dans le terminal `rakudobrew build-panda`

.OSX
Suivez les mêmes étapes indiquées pour l'installation sur Linux +
ou +
Installer avec homebrew: `brew install rakudo-star`

.Windows
. Téléchargez l'installateur le plus récent (fichier avec une extension .MSI) de http://rakudo.org/downloads/star/ +
Si votre système possède une architecture 32-bit, téléchargez le fichier x86. S'il possède une architecture 64-bit téléchargez le fichier x86_64.
. Apres l'installation, ajouter C:\rakudo\bin a votre PATH

.Docker
. Obtenez l'image officielle `docker pull rakudo-star`
. Ensuite exécutez `docker run -it rakudo-star`

=== Exécuter Perl 6
Pour exécuter un code écrit en Perl 6 vous pouvez utiliser le REPL (Read-Eval-Print Loop). +
Dans votre terminal, tapez `perl6`, tapez votre code et pressez [Enter] +

Alternativement, vous pouvez écrire votre code dans un fichier, l'enregistrer et puis l'exécuter. +
Il est recommandé de créer les fichiers Perl 6 avec l'extension `.pl6`. +
Exécutez le fichier du terminal en utilisant cette syntaxe: `perl6 filename.pl6`

Le REPL est surtout utilisé pour essayer un morceau de code, typiquement une unique ligne de code. +
Pour les programmes contenant plusieurs lignes, il est recommandé de les stocker dans un fichier, puis de les exécuter.

=== Editeurs

Comme la plupart du temps, nous allons écrire et stocker nos programmes en Perl 6 dans des fichiers,
nous devrions avoir un éditeur de texte décent qui reconnaît la syntaxe de Perl 6.

Je recommande personnellement https://atom.io/[Atom]. C'est un éditeur de texte moderne livré avec une coloration syntaxique pour Perl 6.

D'autres personnes de la communauté utilisent aussi http://www.vim.org/[Vim], https://www.gnu.org/software/emacs/[Emacs] ou http://padre.perlide.org/[Padre].

Les versions récentes de Vim sont livrées avec la coloration syntaxique pour Perl 6. Emacs et Padre nécessiteront l'installation de paquets supplémentaires.


=== Hello World!
Nous allons commencer avec le rituel `hello world`.

[source,perl6]
say 'hello world';

=== Aperçu de la syntaxe
Perl 6 est en *forme libre*: Vous êtes libre (la plupart du temps) à utiliser n'importe quelle quantité d'espaces.

Les *Instructions* sont typiquement une ligne logique de code, un point-virgule est nécessaire à leur fin: +
`say "Hello" if True;`

Les *Expressions* sont un type spécial d'instructions qui retournent une valeur: +
`1+2` retourne `3`

Les expressions sont faites de *Termes* et d'*Operateurs*.

Les *Termes* sont des:

* *Variables*: Une valeur qui peut être manipulée ou changée.

* *Littérales*: Une valeur constante comme un nombre ou une chaîne.

Les *Opérateurs* sont classés en types:

|===

| *Type* | *Explication* | *Exemple*

| Préfixe | Avant le terme. | `++1`

| Infixe | Entre deux termes. | `1+2`

| Suffixe | Après le terme. | `1++`

| Circonfixe | Autour du terme. | `(1)`

| Postcirconfixe | Après un terme, autour d'un autre  | `Array[1]`

|===

==== Identificateurs
Les identificateurs sont le nom donné aux termes lors de leur définition.

.Règles:
* Ils doivent commencer par un caractère alphabétique ou un tiret bas (under score).

* Ils peuvent contenir des chiffres (à l'exception du premier caractère).

* Ils peuvent contenir des tirets ou des apostrophes (sauf le premier et le dernier caractère),
mais avec un caractère alphabétique sur le côté droit de chaque tiret / apostrophe.

|===

| *Valide* | *Non valide*

| `var1` | `1var`

| `var-one` | `var-1`

| `var'one` | `var'1`

| `var1_` | `var1'`

| `_var` | `-var`

|===

.Conventions de nommage:
* Camel: `variableNo1`

* Kebab: `variable-no1`

* Snake: `variable_no1`

Vous êtes libre de nommer vos identificateurs comme vous le souhaitez,
mais choisissez une convention de nommage et tenez-vous y.

L'utilisation de noms signifiants facilitera votre vie et celle des autres. +
`var1 = var2 * var3` est syntaxiquement correct mais son but n'est pas évident. +
`monthly-salary = daily-rate * working-days` serait une meilleure façon de nommer vos variables.

==== Commentaires
Un commentaire est du texte ignoré par le compilateur.

Il y a 3 types de commentaires:

* Ligne unique:
+
[source,perl6]
#Ceci est une seule ligne de commentaire

* Intégré:
+
[source,perl6]
say #`(Ceci est un commentaire intégré) "Hello World."

* Multi ligne:
+
[source,perl6]
-----------------------------
=begin comment
Ceci est un commentaire sur plusieurs lignes.
Commentaire 1
Commentaire 2
=end comment
-----------------------------

==== Guillemets
Les chaînes doivent être délimitées par des guillemets droits doubles ou simples.

Utilisez toujours des guillemets droits doubles:

* si votre chaîne contient une apostrophe.

* si votre chaîne contient une variable qui doit être interpolée.

[source,perl6]
-----------------------------------
say 'Hello World';               #Hello World
say "Hello World";               #Hello World
say "Quelqu'un m'a dit";         #Quelqu'un m'a dit
my $nom = 'Jean Dupont';
say 'Salut $name';               #Salut $nom
say "Salut $name";               #Salut Jean Dupont
-----------------------------------

== Operateurs
[cols="^.^5m,^.^5m,.^20,.^20m,.^20m", options="header"]
|===

| Operateur | Type | Description | Exemple | Résultat

| + | Infixe | Addition | 1 + 2 | 3

| - | Infixe | Soustraction | 3 - 1 | 2

| * | Infixe | Multiplication | 3 * 2 | 6

| ** | Infixe | Puissance | 3 ** 2 | 9

| / | Infixe | Division | 3 / 2 | 1.5

| div | Infixe | Division (arrondi) | 3 div 2 | 1

| % | Infixe | Reste | 7 % 4 | 3

.2+| %% .2+| Infixe .2+| Divisibilité | 6 %% 4 | False

<| 6 %% 3 <| True

| gcd | Infixe | Plus grand dénominateur commun | 6 gcd 9 | 3

| lcm | Infixe | Plus petit commun multiple | 6 lcm 9 | 18

| == | Infixe | Egalité | 9 == 7  | False

| != | Infixe | Inégalité | 9 != 7  | True

| < | Infixe | Plus petit | 9 < 7  | False

| > | Infixe | Plus grand | 9 > 7  | True

| \<= | Infixe | Plus petit ou égal | 7 \<= 7  | True

| >= | Infixe | Plus grand ou égal | 9 >= 7  | True

| eq | Infixe | Egalité (chaînes) | "John" eq "John"  | True

| ne | Infixe | Inégalité (chaînes) | "John" ne "Jane"  | True

| = | Infixe | Affectation | my $var = 7  | Attribue la valeur `7` a la variable `$var`

.2+| ~ .2+| Infixe .2+| Concaténation | 9 ~ 7 | 97

<m| "Hi " ~ "there"  <| Hi there

.2+| x .2+| Infixe .2+| Réplication | 13 x 3  | 131313

<| "Hello " x 3  <| Hello Hello Hello

| ~~ | Infixe | Smart match |   |

.2+| ++ | Préfixe | Incrémentation | my $var = 2; ++$var;  | Incrémente la variable de 1 et retourne le résultat `3`

<m| Suffixe <d| Incrémentation <m| my $var = 2; $var++;  <| Retourne la variable `2` et puis l'incrémente

.2+|\--| Préfixe | Décrémentation | my $var = 2; --$var;  | Décrémente la variable de 1 et retourne le résultat `1`

<m| Suffixe <d| Décrémentation <m| my $var = 2; $var--;  <| Retourne la variable `2` et puis la décrémente

.3+| + .3+| Préfixe .3+| Force l'opérande a une valeur numérique | +"3"  | 3

<| +True <| 1

<| +False <| 0

.3+| - .3+| Préfixe .3+| Force l'opérande a une valeur numérique et retourne la négation | -"3"  | -3

<| -True <| -1

<| -False <| 0

.6+| ? .6+| Préfixe .6+| Force l'opérande a une valeur booléenne | ?0 | False

<| ?9.8 <| True

<| ?"Hello" <| True

<| ?"" <| False

<| my $var; ?$var; <| False

<| my $var = 7; ?$var; <| True

| ! | Préfixe | Force l'opérande a une valeur booléenne et retourne la négation | !4 | False

| .. | Infixe | Construction de gammes |  0..5  | Crée une gamme de 0 a 5

| ..^ | Infixe | Construction de gammes |  0..^5  | Crée une gamme de 0 a 4

| ^.. | Infixe | Construction de gammes |  0^..5  | Crée une gamme de 1 a 5

| \^..^ | Infixe | Construction de gammes |  0\^..^5  | Crée une gamme de 1 a 4

| ^ | Préfixe | Construction de gammes |  ^5  | Comme 0..^5 Crée une gamme de 0 a 4

| ... | Infixe | Construction de listes paresseuses |  0...9999  |  Retourne les éléments seulement si nécessaire

.2+| {vbar} .2+| Préfixe .2+| Aplanissement | {vbar}(0..5)  | (0 1 2 3 4 5)

<| {vbar}(0\^..^5)  <| (1 2 3 4)

|===

NOTE: Pour la liste complète des opérateurs, y compris leur priorité: http://doc.perl6.org/language/operators

== Variables
Les variables sont classés en 3 catégories: Scalaires, Tableaux et Hachages.

Un *sigil* (Signe en Latin) est un caractère utilisé comme préfixe pour classer les variables.

* `$` est utilisé pour les scalaires
* `@` est utilisé pour les tableaux
* `%` est utilisé pour les tables de hachage.

=== Scalaires
Un scalaire tient une valeur ou une référence.

[source,perl6]
----
#Chaine
my $nom = 'Jean Dupont';
say $name;

#Entier
my $age = 99;
say $age;
----

=== Tableaux
Les tableaux sont des listes contenant plusieurs valeurs.

[source,perl6]
----
my @animaux = ['chameau','llama','hibou'];
say @animaux;
----

De nombreuses opérations peuvent être effectuées sur les tableaux comme démontré dans l'exemple suivant:

TIP: Le tilde `~` est utilisé pour la concaténation.

[source,perl6]
.`Script`
----
my @animaux = ['chameau','vicuña','llama'];
say "Le zoo contient " ~ @animaux.elems ~ " animaux";
say "Les animaux sont: " ~ @animaux;
say "Je vais adopter un hibou pour le zoo";
@animaux.push("hibou");
say "Maintenant, mon zoo contient: " ~ @animaux;
say "Le premier animal que nous avons adopté est le " ~ @animaux[0];
@animaux.pop;
say "Malheureusement, le hibou est parti, il ne nous reste que: " ~ @animaux;
say "Nous allons fermer le zoo et laisser un animal seulement";
say "Nous allons laisser partir: " ~ @animaux.splice(1,2) ~ " et laisser le " ~ @animaux;
----

.`Output`
----
Le zoo contient 3 animaux
Les animaux sont: chameau vicuña llama
Je vais adopter un hibou pour le zoo
Maintenant, mon zoo contient: chameau vicuña llama hibou
Le premier animal que nous avons adopté est le chameau
Malheureusement, le hibou est parti, il ne nous reste que: chameau vicuña llama
Nous allons fermer le zoo et laisser un animal seulement
Nous allons laisser partir: vicuña llama et laisser le chameau
----

.Explication
`.elems` retourne le nombre d'éléments contenus dans le tableau. +
`.push()` ajoute un élément au tableau. +
Nous pouvons accéder à un élément spécifique dans le tableau en spécifiant sa position `@animaux[0]`. +
`.pop` supprime le dernier élément du tableau. +
`.splice(a,b)` supprime les `b` éléments a partir de la position `a`.

NOTE: Pour la référence complète des tableaux: http://doc.perl6.org/type/Array

=== Hachage
Un hachage (table de hachage / hash) est un ensemble de paires clef / valeur.

[source,perl6]
----------------------------------------------------
my %capitales = ('Londres','Angleterre','Paris','France');
say %capitales;

#une autre façon succincte de remplir le hachage:
my %capitales = (Londres => 'Angleterre', Paris => 'France');
say %capitales;
----------------------------------------------------

=== Types
Dans les exemples précédents, on n'a pas précisé quel type de valeurs les variables peuvent tenir.

TIP: `.WHAT` retournera le type de la valeur contenue dans la variable.

[source,perl6]
---------------------
my $var = 'Text';
say $var;
say $var.WHAT;

$var = 123;
say $var;
say $var.WHAT;
---------------------

Comme vous pouvez le voir dans l'exemple ci-dessus, le type de valeur contenu dans `$var` était (Str) et puis (Int).

Ce style de programmation est appelé le typage dynamique.
Dynamique dans le sens que les variables peuvent contenir des valeurs de tout type.

Maintenant, essayez d'exécuter l'exemple ci-dessous: +
Remarquez `Int` avant le nom de la variable.

[source,perl6]
-----------------------------------------
my Int $var = 'Text';
say $var;
say $var.WHAT;
-----------------------------------------

Il va échouer et retourner ce message d'erreur: `Type check failed in assignment to $var; expected Int but got Str`

Ce qui est arrivé est que nous avons précisé au préalable que la variable doit être de type (Int).
Quand nous avons essayé de lui affecter un (Str), le programme a échoué.

Ce style de programmation est appelé le typage statique. Statique dans le sens que les types de variables sont définies avant l'affectation et ne peuvent pas changer.

Perl 6 possède un *typage graduel*; les deux typages *statique* et *dynamique* peuvent être utilisés.

Voici une liste des types les plus couramment utilisés. +
Les deux premiers ne seront probablement jamais utilisés, mais ils sont répertoriés à titre informatif.

[cols="^.^1m,.^3m,.^2m,.^1m, options="header"]
|===

| *Type* | *Description* | *Exemple* | *Résultat*

| Mu | La racine de la hiérarchie de types | |

| Any | Classe de base par défaut pour les nouvelles classes et pour la plupart des classes intégrées | |

| Cool | Valeur qui peut être considérée comme une chaîne ou un nombre interchangeable | my Cool $var = 31; say $var.flip; say $var * 2; | 13 62

| Str | Chaîne de caractères | my Str $var = "NEON"; say $var.flip; | NOEN

| Int | Entier (précision arbitraire) | 7 + 7 | 14

| Rat | Nombre rationnel (précision limitée) | 0.1 + 0.2 | 0.3

| Bool | Booléen | !True | False

|===

=== Introspection

L'introspection est le processus d'obtention d'informations sur les propriétés d'un objet comme son type. +
Dans l'exemple précédent, nous avons utilisé `.WHAT` pour recevoir le type de la variable.

[source,perl6]
----
my Int $var;
say $var.WHAT;
my $var2;
say $var2.WHAT;
$var2 = 1;
say $var2.WHAT;
$var2 = "Hello";
say $var2.WHAT;
$var2 = True;
say $var2.WHAT;
$var2 = Nil;
say $var2.WHAT;
----

----
(Int)
(Any)
(Int)
(Str)
(Bool)
(Any)
----

Le type d'une variable contenant une valeur est corrélée à sa valeur. +
Le type d'une variable vide fortement déclarée est le type avec lequel elle a été déclarée. +
Le type d'une variable vide qui n'a pas été déclarée fortement est `(Any)` +
Pour vider la valeur d'une variable, vous pouvez lui affecter `Nil`.

=== Portée
Avant d'utiliser une variable pour la première fois, elle doit être déclarée.

Plusieurs déclarateurs peuvent être utilisés dans Perl 6, `my` est ce que nous avons utilisé jusqu'ici.

[source,perl6]
my $var=1;

Le déclarateur `my` donne à la variable une portée *lexicale*.
En d'autres termes, la variable ne sera accessible que dans le même bloc ou elle a été déclarée.

Un bloc en Perl 6 est délimité par `{ }`.
Si aucun bloc n'est trouvé, la variable sera disponible dans l'ensemble du script.

[source,perl6]
--------------------------------
{
  my Str $var = 'Text';
  say $var; #accessible
}
say $var; #inaccessible, renvoie une erreur
--------------------------------

Comme une variable est uniquement accessible dans le bloc où elle est définie, le même nom de variable peut être redéfini dans un autre bloc.

[source,perl6]
----
{
  my Str $var = 'Text';
  say $var;
}
my Int $var = 123;
say $var;
----

=== Affectation vs. Lien
Nous avons vu dans les exemples précédents, comment *affecter* des valeurs aux variables. +
L'*affectation* est faite en utilisant l'opérateur `=`
[source,perl6]
----
my Int $var = 123;
say $var;
----

Nous pouvons modifier la valeur attribuée à une variable:

[source,perl6]
.Affecter
----
my Int $var = 123;
say $var;
$var = 999;
say $var;
----

.`Output`
----
123
999
----

D'autre part, nous ne pouvons pas changer la valeur *liée* à une variable. +
Le *lien* est fait en utilisant l'opérateur `:=`

[source,perl6]
.Lier
----
my Int $var := 123;
say $var;
$var = 999;
say $var;
----

.`Output`
----
123
Cannot assign to an immutable value
----

[source,perl6]
.Une variables peut être également liée a une autre:
----
my $a;
my $b;
$a := $b;
$b = 7;
say $a;
----

NOTE: Pour plus d'informations sur les variables, rendez-vous à http://doc.perl6.org/language/variables

== Fonctions normales et fonctions mutantes

Il est important de différencier entre les fonctions normales et les fonctions mutantes. +
Les fonctions normales ne changent pas l'état initial de l'objet. +
Les fonctions mutantes modifient l'état de l'objet.

[source,perl6,linenums]
.`Script`
----
my @numeros = [7,2,4,9,11,3];

@numeros.push(99);
say @numeros;      #1

say @numeros.sort; #2
say @numeros;      #3

@numeros.=sort;
say @numeros;      #4
----

.`Output`
----
[7 2 4 9 11 3 99] #1
(2 3 4 7 9 11 99) #2
[7 2 4 9 11 3 99] #3
[2 3 4 7 9 11 99] #4
----

.Explication
`.push` est une fonction mutante, elle change l'état du tableau (#1)

`.sort` est une fonction normale, elle retourne un tableau trié, mais ne modifie pas l'état initial du tableau:

* (#2) démontre le retour d'un tableau trié

* (#3) démontre que le tableau initial reste non modifie.

Afin de forcer une fonction normale à agir comme une fonction mutante, nous pouvons utiliser `.=` a la place de `.` (#4) (Ligne 9 du script)

== Structures conditionnelles et boucles
Perl 6 possède une multitude de structures conditionnelles et structures de boucles.

=== if
Le code ne fonctionne que si la condition a été remplie.

[source,perl6]
----
my $age = 19;

if $age > 18 {
  say 'Bienvenue'
}
----

En Perl 6, nous pouvons inverser le code et la condition. +
Même si le code et la condition ont été inversées, la condition est toujours évaluée en premier.

[source,perl6]
----
my $age = 19;

say 'Bienvenue' if $age > 18;
----

Si la condition n'est pas remplie, nous pouvons toujours préciser des blocs d'exécution alternatifs en utilisant:

* `else`
* `elsif`

[source,perl6]
----
#exécuter le même code pour différentes valeurs de la variable
my $nombre-de-places = 9;

if $nombre-de-places <= 5 {
  say 'Je suis une berline'
} elsif $nombre-de-places <= 7 {
  say 'Je suis un monospace'
} else {
  say 'Je suis un van'
}
----

=== unless
La version négative d'un `if` peut être écrite en utilisant `unless`.

Le code suivant:

[source,perl6]
----
my $chaussures-propres = False;

if not $chaussures-propres {
  say 'Nettoyez vos chaussures'
}
----
peut aussi être écrit ainsi:

[source,perl6]
----
my $chaussures-propres = False;

unless $chaussures-propres {
  say 'Nettoyez vos chaussures'
}
----

La négation en Perl 6 est faite en utilisant `!` ou `not`.

`unless (condition)` est utilisé à la place de `if not (condition)`.

`unless` ne peux pas avoir une clause `else`.

=== with

`with` fonctionne comme `if`, mais vérifie si la variable est définie.

[source,perl6]
----
my Int $var=1;

with $var {
  say 'Bonjour'
}
----

Si vous exécutez le code sans attribuer une valeur à la variable, rien ne devrait arriver.
[source,perl6]
----
my Int $var;

with $var {
  say 'Bonjour'
}
----

`without` est la version négative de `with`. Vous devriez être capable de le relier le concept à `unless`.

Si la première condition `with` n'est pas remplie, un autre chemin peut être spécifié en utilisant `orwith`. +
`with` et `orwith` peuvent être comparés à `if` et `elsif`.

=== for

La boucle `for` itère sur plusieures valeurs.

[source,perl6]
----
my @array = [1,2,3];

for @array -> $array-item {
  say $array-item*100
}
----

Notez que nous avons créé une variable d'itération `$array-item` afin d'effectuer l'opération `*100` sur chaque élément du tableau.

=== given

`given` est l'équivalent Perl 6 de l'instruction switch dans d'autres langues.

[source,perl6]
----
my $var = 42;

given $var {
    when 0..50 { say 'Plus petit que 50'}
    when Int { say "est un Int" }
    when 42  { say 42 }
    default  { say "huh?" }
}
----

Après un appariement réussi, le processus d'appariement arrêtera.

Alternativement `proceed` instruira Perl 6 à poursuivre l'appariement, même après un appariement réussi.
[source,perl6]
----
my $var = 42;

given $var {
    when 0..50 { say 'Plus petit que 50';proceed}
    when Int { say "est un Int";proceed}
    when 42  { say 42 }
    default  { say "huh?" }
}
----

=== loop

`loop` est une autre façon d'écrire une boucle `for`.

En fait `loop` est comment les boucles `for` sont écrites dans les langages de programmation appartenant a la famille-C.

Perl 6 appartient à la famille-C

[source,perl6]
----
loop (my $i=0; $i < 5; $i++) {
  say "Le nombre actuel est $i"
}
----

NOTE: Pour plus d'informations sur les boucles et les conditions, voir http://doc.perl6.org/language/control

== E/S
En Perl 6, deux des interfaces _entrée/sortie_ les plus communes sont le _Terminal_ et les _Fichiers_.

=== E/S Basic en utilisant le Terminal

==== say
`say` écrit sur l'interface de sortie standard. Il ajoute une nouvelle ligne à la fin. En d'autres termes, le code suivant:

[source,perl6]
----
say 'Bonjour Madame.';
say 'Bonjour Monsieur.';
----
sera écrit sur 2 lignes distinctes.

==== print
`print` d'autre part fonctionne comme `say` mais sans ajouter une nouvelle ligne.

Essayez de remplacer `say` avec `print` et de comparer les deux résultats.

==== get
`get` est utilisé pour capturer l'entrée du Terminal.

[source,perl6]
----
my $nom;

say "Salut quel est ton nom?";
$nom=get;

say "Cher $nom bienvenue à Perl 6";
----

Lorsque le code ci-dessus est lancé, le terminal vous attendra pour saisir votre nom.
Par la suite, il vous accueillera.

==== prompt
`prompt` est une combinaison de `print` et `get`.

L'exemple ci-dessus peut être écrit comme ceci:

[source,perl6]
----
my $nom = prompt("Salut quel est ton nom? ");

say "Cher $nom bienvenue à Perl 6";
----

=== Exécution de commandes Shell
Deux sous-programmes peuvent être utilisés pour exécuter des commandes shell:

* `run` Exécute une commande externe sans impliquer le Shell

* `shell` Exécute une commande via le shell. Tous les méta-caractères sont interprétés par le shell, y compris les tuyaux, les redirections, les variables d'environnement etc.

[source,perl6]
----
my $nom = 'Neo';
my $commande = run 'echo', "salut $name";
my $commande2 = shell "ls";
----
`echo` et `ls` sont des mots clés communs de shell. +
`echo` imprime le texte sur le Terminal (l'équivalent de `print` en Perl 6) +
`ls` liste tous les fichiers et dossiers dans le répertoire courant


=== E/S Fichier
==== slurp
`slurp` est utilisé pour lire les données d'un fichier.

Créez un fichier texte avec le contenu suivant:

.datafile.txt
----
John 9
Johnnie 7
Jane 8
Joanna 7
----
[source,perl6]
----
my $data = slurp "datafile.txt";
say $data;
----

==== spurt
`spurt` est utilisé pour écrire des données sur un fichier.

[source,perl6]
----
my $newdata = "New scores:
Paul 10
Paulie 9
Paulo 11";

spurt "newdatafile.txt", $newdata;
----

Après avoir exécuté le code ci-dessus, un nouveau fichier nommé _newdatafile.txt_ sera créé. Il contiendra les nouveaux scores.

=== Travailler avec les fichiers et répertoires
Perl 6 peut lister le contenu d'un répertoire sans exécuter des commandes shell (en utilisant `ls`) comme nous l'avons vu dans un exemple précédent.

[source,perl6]
----
say dir;              #Liste les fichiers et dossiers dans le répertoire courant
say dir "/Documents"; #Liste les fichiers et dossiers dans le répertoire spécifié
----

De plus, vous pouvez créer de nouveaux dossiers et les supprimer.

[source,perl6]
----
mkdir "newfolder";
rmdir "newfolder";
----

`mkdir` crée un nouveau répertoire. +
`rmdir` supprimer un répertoire vide. Renvoie une erreur s'il n'est pas vide.

Vous pouvez également vérifier si le chemin d'accès spécifié existe, s'il est un fichier ou un répertoire:

Dans le répertoire où vous allez exécutez le script ci-dessous, créez un dossier vide `folder123` et un fichier .pl6 vide `script123.pl6`

[source,perl6]
----
say "script123.pl6".IO.e;
say "folder123".IO.e;

say "script123.pl6".IO.d;
say "folder123".IO.d;

say "script123.pl6".IO.f;
say "folder123".IO.f;
----

`IO.e` vérifie si le répertoire/fichier existe. +
`IO.f` vérifie si c'est un fichier. +
`IO.d` vérifie si c'est un dossier.

NOTE: Pour plus d'informations sur les E/S, voir http://doc.perl6.org/type/IO
