= Perl 6 Inleiding
Naoum Hankache <naoum@hankache.com>; Elizabeth Mattijsen <perl6intro@liz.nl>
:description: Een algemene inleiding van Perl 6
:keywords: perl6, perl 6, inleiding, perl6intro, perl 6 inleiding, perl 6 tutorial, perl 6 intro
:Revision: 1.0
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:doctype: book
:lang: nl

Dit document is bedoeld om je een kort overzicht te geven van de Perl 6 programmeertaal.
Het is zo opgezet dat je snel leert iets met Perl 6 te kunnen doen.

Sommige onderdelen van dit document verwijzen aan (completere en preciezere) delen van de (Engelstalige) http://docs.perl6.org[Perl 6 documentatie].
Als je meer informatie over een bepaald onderwerp nodig hebt, is dat de beste plaats om die te vinden.

Je zult voorbeelden vinden bij de meeste onderwerpen in dit document.
Neem de tijd om ze allemaal uit te proberen om ze beter te begrijpen.

.Licentie
De inhoud is gelicenseerd met de Creative Commons Attribution-ShareAlike 4.0 International License.
Om deze in te zien, ga naar

* https://creativecommons.org/licenses/by-sa/4.0/.

.Bijdragen
Als je wilt bijdragen aan dit document, ga dan naar:

* https://github.com/hankache/perl6intro

.Feedback
Alle feedback is welkom:

* naoum@hankache.com - Engels
* perl6intro@liz.nl - Nederlands

:sectnums:
== Inleiding
=== Wat is Perl 6
Perl 6 is een hogere programmeertaal voor algemeen gebruik met graduele typering.
In Perl 6 kan met diverse paradigma's geprogrammeerd worden.  Ondersteund worden onder andere procedureel, object-georienteerd en functioneel programmeren.

.Perl 6 motto:
* TIMTOWTDI (uitgesproken "Timtoodi", oftewel "TimToady" in het Engels): There Is More Than One Way To Do It. (Er is meer dan één manier om het te doen)
* Gemakkelijke dingen moeten gemakkelijk blijven, moeilijke dingen moeten gemakkelijker worden en onmogelijk dingen moeten slechts moeilijk zijn.

=== Jargon
* *Perl 6*: Is een taalspecificatie met een verzameling tests.
Een implementatie van Perl 6 die al deze tests succesvol kan uitvoeren, mag zich een "Perl 6" implementatie noemen.
* *Rakudo*: Is een compiler voor Perl 6.
* *Rakudobrew*: Is een installatie-manager van Perl 6.
* *Panda*: Is een installatie-programma voor modules.
* *Rakudo Star*: Is een bundel software waarin zich Rakudo, Panda, documentatie en een verzameling van Perl 6 modules bevindt.

=== Installeren van Perl 6
.Linux
. Installeer Rakudobrew: https://github.com/tadzik/rakudobrew

. Installeer Rakudo: Typ het volgende commando in een terminalvenster `rakudobrew build moar`

. Installeer Panda: Typ het volgende commando in een terminalvenster `rakudobrew build panda`

.OSX
OS X kent vier mogelijkheden:

* Volg dezelfde stappen als voor Linux

* Installeer met homebrew: `brew install rakudo-star`

* Installeer met MacPorts: `sudo port install rakudo`

* Download de meest recente installer (bestand met .dmg extensie) van http://rakudo.org/downloads/star/

.Windows
. Download de meest recente installer (bestand met .msi extensie) van http://rakudo.org/downloads/star/ +
Op een 32-bit systeem, download het bestand met x86; op een 64-bit, download het x86_64 bestand.
. Zorg ervoor dat `C:\rakudo\bin` in je PATH is na het installeren.

.Docker
. Gebruik het officiele Docker image `docker pull rakudo-star`
. Voer daarna een container uit met het image `docker run -it rakudo-star`

=== Uitvoeren van Perl 6 code

Je kunt eenvoudig Perl 6 code uitvoeren in de REPL (Read-Eval-Print-Loop, oftewel een lees, evalueer, print, lus).
Open daarvoor een terminalvenster, type `perl6` en druk op [Enter].  Er verschijnt dan een `>` prompt.
Vervolgens kun je een regel code intypen en weer op [Enter] drukken.  De REPL zal dan de uiteindelijke waarde van die code afdrukken op het scherm.  Je kunt dan weer een regel code intypen, of `exit` intypen en op [Enter] drukken om de REPL te verlaten.

Je kunt je code natuurlijk ook opslaan in een bestand, dat je daarna gaat uitvoeren.
We raden aan om een Perl 6 script de extensie `.pl6` te geven, zodat het later te herkennen is als Perl 6 bestand.
Voer het bestand uit door `perl6 bestandsnaam.pl6` in het terminal venster in te typen en op [Enter] te drukken.  Anders dan bij de REPL zal die niet automatisch het resultaat van elke regel afdrukken: daarvoor moet je een opdracht als `say` in je programma plaatsen om iets af te drukken.

De REPL wordt meestal gebruikt om een specifiek stukje code uit te proberen, meestal niet meer dan een enkele regel.  Voor programma's die uit meer dan een regel bestaan, wordt aangeraden om die regels in een bestand op te slaan en dan dat bestand uit te voeren.

Je kunt ook een regel code non-interactief uitproberen op de commando-regel in een terminal venster, door `perl6 -e 'jouw regel code'` in te typen en dan op [Enter] te drukken.

[TIP]
--
In de bundel Rakudo Star zit ook een regel-editor die het uitproberen in de REPL nog gemakkelijker maakt.

Als je alleen maar Rakudo hebt geinstalleerd, en niet Rakudo Star, dan heb je standaard niet alle handige regel-editor mogelijkheden (zoals pijltje naar onder/boven om eerder ingetypte regels te bekijken, pijltje links/rechts om je invoer te veranderen, en automatisch invullen met TAB).
Voer het volgende commando uit om deze functionaliteit te installeren:

* `panda install Linenoise` werkt op Windows, Linux en OSX

* `panda install Readline` als je op Linux werkt en liever werkt met de _Readline_ bibliotheek
--

=== Bewerkingsprogramma's (Editors)
Aangezien je het grootste deel van je tijd Perl 6 programma's in bestanden aan het opslaan bent, is het handig om een goede editor te hebben die Perl 6 syntax herkent.

Ik gebruik https://atom.io/[Atom] en raadt het gebruik daarvan ook een.  Het is een moderne tekst-editor die standaard uitgeleverd wordt met Perl 6 syntax-markeeerder.
https://atom.io/packages/language-perl6fe[Perl6-fe] is een alternatieve Perl 6 syntax-markeerder voor Atom, afgeleid van het origineel, maar met vele bug-fixes en toevoegingen.

Andere mensen in de gemeenschap gebruiken ook http://www.vim.org/[Vim], https://www.gnu.org/software/emacs/[Emacs] of http://padre.perlide.org/[Padre].

Recente versies van Vim worden standaard uitgeleverd met een syntax-markeerder. Emacs en Padre hebben de installatie van extra bibliotheken nodig.


=== Hello World!
Laten we beginnen met het `hello world` ritueel.

[source,perl6]
say 'hello world';

hetgeen ook geschreven kan worden als:

[source,perl6]
'hello world'.say;

=== Syntax overview
Perl 6 kent weinig beperkingen: over het algemeen kun je zoveel spaties (witregels) gebruiken als je zelf wilt.

Opdrachten bestaan over het algemeen uit een regel code die beeindigd wordt door een punt-komma.
`say "Hallo" if True;`

*Expressies* zijn een speciaal soort opdracht die resulteren in een waarde:
`1+2` geeft `3` terug

Expressies bestaan uit *Termen* en *Operatoren*.

*Termen* zijn:

* *Variabelen*: Een waarde die bekeken en veranderd kan worden.

* *Literals* (Letterlijke waarden): een constante waard zoals een getal of een aantal letters (string).

*Operatoren* worden onderverdeeld in deze typen:

|===

| *Type* | *Uitleg* | *Voorbeeld*

| Prefix | Voor de term. | `++1`

| Infix | Tussen twee termen | `1+2`

| Postfix | Volgt na een term | `1++`

| Circumfix | Staat om een term heen | `(1)`

| Postcircumfix | Achter een term, om een andere term heen  | `Array[1]`

|===

==== Naamgeving
Je moet termen een naam geven op het moment dat je ze definieert.

.Regels:
* Ze moeten beginnen met een alphabetisch karakter of een underscore.

* Ze mogen cijfers bevatten (behalve als eerste karakter).

* Ze mogen een of meer koppeltekens `-` en/of enkele aanhalingstekens `'` bevatten (mits omgeven door alphabetische karakters, dus niet als eerste of laatste karakter).

|===

| *Geldig* | *Niet geldig*

| `var1` | `1var`

| `var-one` | `var-1`

| `var'one` | `var'1`

| `var1_` | `var1'`

| `_var` | `-var`

|===

.Naamgevingsconventies:
* Kameelkast (Camel case): `variableNo1`

* Kebabkast (Kebab case): `variable-no1`

* Slangenkast (Snake case): `variable_no1`

Je mag je termen namen geven zoals je zelf wilt, maar het is een goede gewoonte om vast te houden aan een enkele naamgevingsconventie in een programma.

Het gebruik van betekenisvolle namen zal jouw leven als programmeur gemakkelijker maken (en van anderen die later aan jouw programma moeten werken).

* `var1 = var2 * var3` is syntactisch correct, maar de betekenis is niet duidelijk.
* `maandsalaris = dagloon * gewerkte-dagen` geeft beter aan waar het hierover gaat.

==== Commentaar
Een commentaar is een stuk tekst dat bij uitvoering genegeerd wordt, maar van belang kan zijn voor de lezer van de programma-code.

Er zijn 3 manieren om commentaren in een programma te stoppen:

* Enkele regel;
+
[source,perl6]
# Dit is een regel met commentaar

* Ingebed (embedded):
+
[source,perl6]
say #`(Dit is een ingebed commentaar) "Hello World."

* Meer dan 1 regel
+
[source,perl6]
-----------------------------
=begin comment
Dit is een commentaar over meer dan 1 regel
Commentaar 1
Commentaar 2
=end comment
-----------------------------

==== Aanhalingstekens (Quotes)
Een string wordt gedefinieerd door middel van enkele of dubbele aanhalingstekens.

Gebruik altijd dubbele aanhalingstekens:

* als er een enkel aanhalingsteken in de string voorkomt.

* indien de string een variabele bevat die geinterpoleerd moet worden.

[source,perl6]
---------------------------------------
say 'Hallo Wereld';   # Hallo Wereld
say "Hallo Wereld";   # Hallo Wereld
say "Doe 't niet";    # Doe 't niet
my $naam = 'Jan Jansen';
say 'Hallo $naam';   # Hallo $naam
say "Hallo $naam";   # Hallo Jan Jansen
---------------------------------------

== Operatoren

=== Algemene operatoren
Onderstaande tabel toont de meest voorkomende operatoren.
[cols="^.^5m,^.^5m,.^20,.^20m,.^20m", options="header"]
|===

| Operator | Type | Beschrijving | Voorbeeld | Resultaat

| + | Infix | Optelling | 1 + 2 | 3

| - | Infix | Aftrekking | 3 - 1 | 2

| * | Infix | Vermenigvuldiging | 3 * 2 | 6

| ** | Infix | Machtsverheffen | 3 ** 2 | 9

| / | Infix | Delen | 3 / 2 | 1.5

| div | Infix | Geheel getal deling (rond af) | 3 div 2 | 1

| % | Infix | Modulo | 7 % 4 | 3

.2+| %% .2+| Infix .2+| Deelbaarheid | 6 %% 4 | False

<| 6 %% 3 <| True

| gcd | Infix | Grootse gemene deler | 6 gcd 9 | 3

| lcm | Infix | Kleinste gemene veelvoud | 6 lcm 9 | 18

| == | Infix | Numeriek gelijk | 9 == 7  | False

| != | Infix | Numeriek ongelijk | 9 != 7  | True

| < | Infix | Numeriek kleiner dan | 9 < 7  | False

| > | Infix | Numeriek groter dan | 9 > 7  | True

| \<= | Infix | Numeriek kleiner dan of gelijk aan | 7 \<= 7  | True

| >= | Infix | Numeriek groter dan of gelijk aan | 9 >= 7  | True

| eq | Infix | String gelijk | "Jan" eq "Jan"  | True

| ne | Infix | String ongelijk | "Jan" ne "Jolanda"  | True

| = | Infix | Toewijzing | my $var = 7  | Wijst de waarde `7` toe aan de variabele `$var`

.2+| ~ .2+| Infix .2+| Letterreeks aaneenschakelen | 9 ~ 7 | 97

<m| "Hi " ~ "there"  <| Hi there

.2+| x .2+| Infix .2+| Letterreeks herhalen | 13 x 3  | 131313

<| "Hello " x 3  <| Hello Hello Hello

.5+| ~~ .5+| Infix .5+| Slim vergelijken | 2 ~~ 2  | True

<| 2 ~~ Int <| True

<| "Perl 6" ~~ "Perl 6" <| True

<| "Perl 6" ~~ Str <| True

<| "enlightenment" ~~ /light/ <| ｢light｣

.2+| ++ | Prefix | Verhoging | my $var = 2; ++$var;  | Verhoog de variabele met `1` en geef de verhoogde waarde terug: `3`

<m| Postfix <d| Verhoging <m| my $var = 2; $var++;  <| Geef de waarde van de variabele terug (`2`) en verhoog de variabele dan met `1`

.2+|\--| Prefix | Verlaging | my $var = 2; --$var;  | Verlaag de variabele met `1` en geef de verlaagde waarde terug: `1`

<m| Postfix <d| Verlaging <m| my $var = 2; $var--;  <| Geef de waarde van de variabele terug (`2`) en verlaag die dan met `1`

.3+| + .3+| Prefix .3+| Forceer naar de numerieke waarde | +"3"  | 3

<| +True <| 1

<| +False <| 0

.3+| - .3+| Prefix .3+| Forceer naar de negatieve numerieke waarde | -"3"  | -3

<| -True <| -1

<| -False <| 0

.6+| ? .6+| Prefix .6+| Forceer naar de boolean waarde | ?0 | False

<| ?9.8 <| True

<| ?"Hello" <| True

<| ?"" <| False

<| my $var; ?$var; <| False

<| my $var = 7; ?$var; <| True

| ! | Prefix | Forceer naar de tegenovergestelde boolean waarde | !4 | False

| .. | Infix | Lijst constructeur |  0..5  | Maak een lijst van 0 t/m 5

| ..^ | Infix | Lijst constructeur |  0..^5  | Maak een lijst van 0 t/m 4

| ^.. | Infix | Lijst constructeur |  0^..5  | Maak een lijst van 1 t/m 5

| \^..^ | Infix | Lijst constructeur |  0\^..^5  | maak een lijst van 1 t/m 4

| ^ | Prefix | Lijst constructeur |  ^5  | Zelfde als 0..^5, maakt een lijst van 0 t/m 4

| ... | Infix | Luie lijst constructeur |  0...9999  | Maak waarden alleen aan indien daar expliciet om gevraagd wordt

.2+| {vbar} .2+| Prefix .2+| Pletten | {vbar}(0..5)  | (0 1 2 3 4 5)

<| {vbar}(0\^..^5)  <| (1 2 3 4)

|===

=== Reversi operatoren

Door een `R` te plaatsen direct voor een operator, zorg je ervoor dat de termen omgewisseld worden.

[cols=".^m,.^m,.^m,.^m", options="header"]
|===
| Normale operator | Resultaat | Reversi Operator | Resultaat

| 2 / 3 | 0.666667 | 2 R/ 3 | 1.5

| 2 - 1 | 1 | 2 R- 1 | -1

|===

=== Herleidingsoperatoren

Herleidingsoperatoren werken op lijsten.
Je maakt een herleidingsoperator door vierkante haken om de operator te plaatsen `[]`

[cols=".^m,.^m,.^m,.^m", options="header"]
|===
| Normal Operator | Resultaat | Herleidingsoperator | Resultaat

| 1 + 2 + 3 + 4 + 5 | 15 | [+] 1,2,3,4,5 | 15

| 1 * 2 * 3 * 4 * 5 | 120 | [*] 1,2,3,4,5 | 120

|===

NOTE: voor een compleet overzicht van operatoren, inclusief hun prioriteit, ga dan naar https://docs.perl6.org/language/operators

== Variabelen
Perl 6 variabelen kunnen worden geclassificeerd in 3 categorieen: Scalars, Arrays en Hashes.

Een *voorteken* (sigil) is een karakter dat als prefix gebruikt wordt om aan te geven in welke categorie een variabele hoort.

* `$` geeft een scalar aan
* `@` geeft een array aan
* `%` geeft een hash aan

=== Scalars
Een scalar kan 1 waarde bevatten.

[source,perl6]
----
#String
my $naam = 'Jan Jansen';
say $naam;

#Integer
my $leeftijd = 99;
say $leeftijd;
----

Afhankelijk van het type waarde dat een scalar bevat, kun je daar bepaalde operaties op uitvoeren.

[source,perl6]
.String
----
my $naam = 'Jan Jansen';
say $naam.uc;
say $naam.chars;
say $naam.flip;
----

----
JAN JANSEN
10
nesnaJ naJ
----

NOTE: Bekijk https://docs.perl6.org/type/Str voor de complete lijst van methoden die men op een string kan uitvoeren.

[source,perl6]
.Integer
----
my $leeftijd = 17;
say $leeftijd.is-prime;
----

----
True
----

NOTE: Bekijk https://docs.perl6.org/type/Int voor de complete lijst van methoden die men op een geheel getal (integer) kan uitvoeren.

[source,perl6]
.Rational Number
----
my $leeftijd = 2.3;
say $leeftijd.numerator;
say $leeftijd.denominator;
say $leeftijd.nude;
----

----
23
10
(23 10)
----

NOTE: Bekijk https://docs.perl6.org/type/Rat voor de complete lijst van methoden die men op een rationeel getal kan uitvoeren.

=== Arrays
Arrays bestaan uit een lijst van scalar variabelen.

[source,perl6]
----
my @animals = 'camel','llama','owl';
say @animals;
----

Vele operaties kunnen op arrays uitgevoerd worden, zoals getoond in onderstaand voorbeeld:

TIP: De tilde `~` wordt gebruikt om strings aan elkaar te plakken.

[source,perl6]
.`Script`
----
my @animals = 'kameel','vicuña','lama';
say "De dierentuin heeft " ~ @animals.elems ~ " dieren";
say "De dieren zijn: " ~ @animals;
say "Ik ga een uil adopteren voor de dierentuin";
@animals.push("owl");
say "Nu heeft mijn dierentuin: " ~ @animals;
say "Het eerste dier dat we adopteerden was de " ~ @animals[0];
@animals.pop;
say "Helaas is de uil ontsnapt, dus hebben we nu alleen nog: " ~ @animals;
say "We gaan de dierention sluiten en houden nog maar 1 dier over";
say "We laten de " ~ @animals.splice(1,2) ~ " gaan en houden de " ~ @animals;
----

.`Uitvoer`
----
De dierentuin heeft 3 dieren
De dieren zijn: kameel vicuña lama
Ik ga een uil adopteren voor de dierentuin
Nu heeft mijn dierentuin: kameel vicuña lama uil
Het eerste dier dat we adopteerden was de kameel
Helaas is de uil ontsnapt, dus hebben we nu alleen nog: kameel vicuña lama
We gaan de dierention sluiten en houden nog maar 1 dier over
We laten de vicuña llama gaan en houden de kameel
----

.Uitleg
`.elems` geeft het aantal elementen in een array. +
`.push()` voegt een element toe aan een array. +
We kunnen een specifiek element van een array bekijken door de positie aan te geven `@animals[0]`. +
`.pop` verwijdert het laatste element van het array. +
`.splice(a,b)` verwijdert `b` elementen vanaf positie `a`.

==== Arrays met beperkt aantal elementen
Een gewoon array kun je als volgt specificeren:
[source,perl6]
my @array;

Een gewoon array is niet beperkt wat betreft aantal elementen, het past zichzelf aan (auto-extending). +
Men kan in een gewoon array zoveel waarden opslaan als men wil.

Daarentegen is het ook mogelijk om een array aan te maken met een beperkt aantal elementen.
Dit soort arrays verbieden toegang tot niet-bestaande elementen.

Specificeer het aantal elementen in vierkante haken direct achter de naam van een array om een array met beperkt aantal elementen te specificeren:
[source,perl6]
my @array[3];

Dit array kan hoogstens 3 waarden bevatten, met als indexwaarden 0 t/m 2.

[source,perl6]
----
my @array[3];
@array[0] = "eerste waarde";
@array[1] = "tweede waarde";
@array[2] = "derde waarde";
----

Het is niet mogelijk om een vierde waarde aan dit array toe te voegen:
[source,perl6]
----
my @array[3];
@array[0] = "eerste waarde";
@array[1] = "tweede waarde";
@array[2] = "derde waarde";
@array[3] = "vierde waarde";
----

----
Index 3 for dimension 1 out of range (must be 0..2)
----

==== Multidimensionele arrays
De arrays die we tot nu toe gezien hebben, hadden maar 1 dimensie. +
The arrays we saw until now are one-dimensional. +
We kunnen echter ook arrays met meer dan 1 dimensie in Perl 6 specificeren.

[source,perl6]
my @tbl[3;2];

Dit array heeft 2 dimensies.
De eerste dimensie kan maximaal 3 waarden hebben, en de tweede dimensie maximaal 2 waarden.

Zie het als een rooster van 3x2.

[source,perl6]
----
my @tbl[3;2];
@tbl[0;0] = 1;
@tbl[0;1] = "x";
@tbl[1;0] = 2;
@tbl[1;1] = "y";
@tbl[2;0] = 3;
@tbl[2;1] = "z";
say @tbl
----

----
[[1 x] [2 y] [3 z]]
----

.Visuele weergave van het array:
----
[1 x]
[2 y]
[3 z]
----

NOTE: zie https://docs.perl6.org/type/Array voor volledige informatie over arrays.

=== Hashes
[source,perl6]
.Een Hash is een verzameling van naam/waarde paren (key/value pairs)
----
my %hoofdsteden = ('VK','Londen','Duitsland','Berlijn');
say %hoofdsteden;
----

.`Uitvoer`
----
{Duitsland => Berlijn, VK => Londen}
----

[source,perl6]
.Een andere manier om een hash te vullen:
----
my %hoofdsteden = (UK => 'London', Germany => 'Berlin');
say %hoofdsteden;
----

.`Uitvoer`
----
{Duitsland => Berlijn, VK => Londen}
----

Dit zijn een aantal van de methoden die men op een hash kan uitvoeren:
[source,perl6]
.`Script`
----
my %hoofdsteden = (VK => 'Londen', Duitsland => 'Berlijn');
%hoofdsteden.push: (Frankrijk => 'Parijs');
say %hoofdsteden.kv;
say %hoofdsteden.keys;
say %hoofdsteden.values;
say "De hoofdstad van Frankrijk is: " ~ %hoofdsteden<Frankrijk>;
----

.`Uitvoer`
----
(Frankrijk Parijs Duitsland Berlijn VK Londen)
(Frankrijk Duitsland VK)
(Parijs Berlijn Londen)
De hoofdstad van Frankrijk is: Parijs
----

.Uitleg
`.push: (naam => 'Waarde')` voegt een nieuw naam/waarde paar toe. +
`.kv` geeft een lijst met alle namen en waarden terug. +
`.keys` geeft een lijst met alle namen terug. +
`.values` geeft een lijst met alle waarden terug. +
De waarde behorende bij een gegeven naam kun je opvragen door die naam te specificeren `%hash<naam>`

NOTE: Zie https://docs.perl6.org/type/Hash voor alle informatie over hashes.

=== Types
In de voorafgaande voorbeelden hebben we niet het type van de waarde aangegeven die in een variabele opgeslagen kan worden.

TIP: `.WHAT` geeft het type van de waarde in een variabele terug.

[source,perl6]
----
my $var = 'Tekst';
say $var;
say $var.WHAT;

$var = 123;
say $var;
say $var.WHAT;
----

Zoals je kunt zien in bovenstaand voorbeeld, was het type van de waarde in `$var` eerst (Str) en daarna (Int).

Deze stijl van programmeren wordt dynamische typering (dynamic typing) genoemd.  Dynamisch in de betekenis dat de variable waarden mag bevatten van elk (Any) type.

Probeer nu onderstaand voorbeeld uit te voeren: +
Merk op dat we `Int` voor de naam van de variabele hebben geplaatst.

[source,perl6]
----
my Int $var = 'Tekst';
say $var;
say $var.WHAT;
----

Het zal fout gaan en terug komen met dit foutbericht: `Type check failed in assignment to $var; expected Int but got Str`

Wat hier gebeurde is dat we van te voren hadden aangegeven dat de variabele alleen maar (Int) zou accepteren.
Toen we probeerden om er een string (Str) aan toe te wijzen, was dat niet mogelijk en ging het fout.

Deze stijl van programmeren wordt "statische typering" (static typing) genoemd.  Statisch omdat het type van variabelen wordt gedefinieerd voordat er aan wordt toegewezen, en deze later niet kan worden veranderd.

Perl 6 wordt aangeduid met "graduele typering": het laat namelijk zowel *statische* als *dynamische* typering toe.

.Arrays en hashes kunnen ook statisch getypeerd worden:
[source,perl6]
----
my Int @array = 1,2,3;
say @array;
say @array.WHAT;

my Str @veeltalig = "Hello","Salut","Hallo","您好","안녕하세요","こんにちは";
say @veeltalig;
say @veeltalig.WHAT;

my Str %hoofdsteden = (VK => 'Londen', Duitsland => 'Berlijn');
say %hoofdsteden;
say %hoofdsteden.WHAT;

my Int %landennummers = (VK => 44, Duitsland => 49);
say %landennummers;
say %landennummers.WHAT;
----

.Hieronder vind je een lijst van meest voorkomende typen:
Je zult hoogstwaarschijnlijk de eerste twee nooit gebruiken, maar we laten ze hier zien om je te laten weten dat ze bestaan.

[cols="^.^1m,.^3m,.^2m,.^1m, options="header"]
|===

| *Type* | *Beschrijving* | *Voorbeeld* | *Resultaat*

| Mu | De ultieme basis van de Perl 6 typen hierarchie | |

| Any | Het basis type voor nieuwe klassen en de meeste standaard klassen | |

| Cool | Waarden die zowel als string of als number kunnen worden beschouwd | my Cool $var = 31; say $var.flip; say $var * 2; | 13 62

| Str | Een string: reeks van karakters | my Str $var = "NEON"; say $var.flip; | NOEN

| Int | Integer (elke gewenste precisie) | 7 + 7 | 14

| Rat | Rationeel nummer (beperkte precisie) | 0.1 + 0.2 | 0.3

| Bool | Boolean | !True | False

|===

=== Introspectie

Met introspectie bedoelen we het process waarmee we informatie over de eigenschappen van een object kunnen bekijken, zoals het type. +
In een van de vorige voorbeelden gebruikten we `.WHAT` om het type van een variabele te achterhalen.

[source,perl6]
----
my Int $var;
say $var.WHAT;    # (Int)
my $var2;
say $var2.WHAT;   # (Any)
$var2 = 1;
say $var2.WHAT;   # (Int)
$var2 = "Hello";
say $var2.WHAT;   # (Str)
$var2 = True;
say $var2.WHAT;   # (Bool)
$var2 = Nil;
say $var2.WHAT;   # (Any)
----

Het type van een variabele waarin een waarde is opgeslagen, is gecorreleerd aan die waarde. +
Het type van een lege variabele die gespecificeerd is met een type, is het type waarmee het werd gespecificeerd. +
Het type van een lege variabele die niet is gespecificeerd met een type, is `(Any)` +
Om de waarde uit een variabele te verwijderen, kun je de waarde `Nil` toewijzen.

=== Bereik (scoping)
Voordat men een variabele voor de eerste keer kan gebruiken, moet deze worden gespecificeerd.

Dit kan op diverse manieren in Perl 6, `my` is wat we tot nu toe in de bovenstaande voorbeelden hebben gebruikt.

[source,perl6]
my $var=1;

Met `my` geeft men de variabele een *statisch* bereik (ook wel *lexicaal bereik genoemd).
In andere woorden, de variabele zal alleen maar toegankelijk zijn in het gebied (scope) waarin het was gespecificeerd.

Zo'n gebied (scope) wordt in Perl 6 begrensd door `{ }`.
Een variabele zal alleen toegankelijk zijn in een Perl 6 script als er geen gebiedsbegrenzing gevonden wordt.

[source,perl6]
----
{
  my Str $var = 'Tekst';
  say $var; # is toegankelijk
}
say $var; #is niet toegankelijk, geeft een foutmelding
----

Aangzien zo'n variabele alleen toegankelijk is in het gebied waarin het was gedefinieerd, kan men dezelfde naam voor een variabele gebruiken in een ander gebied.

[source,perl6]
----
{
  my Str $var = 'Tekst';
  say $var;
}
my Int $var = 123;
say $var;
----

=== Toewijzing vs. verbinden
We hebben in de vorige voorbeelden gezien hoe we waarden aan variabelen kunnen *toewijzen*. +
*Toewijzing* wordt gedaan met de `=` operator.

[source,perl6]
----
my Int $var = 123;
say $var;
----

We kunnen de waarde van een variabele veranderen:

[source,perl6]
.Toewijzing
----
my Int $var = 123;
say $var;
$var = 999;
say $var;
----

.`Uitvoer`
----
123
999
----

Daarentegen kunnen we de waarde van een variabele niet veranderen als deze is *verbonden* met een variabele. +
*Verbinding* wordt gedaan met de `:=` operator.

[source,perl6]
.Verbinden
----
my Int $var := 123;
say $var;
$var = 999;
say $var;
----

.`Output`
----
123
Cannot assign to an immutable value
----

[source,perl6]
.Variabelen kunnen ook verbonden worden met andere variabelen:
----
my $a;
my $b;
$b := $a;
$a = 7;
say $b;
$b = 8;
say $a;
----

.`Uitvoer`
----
7
8
----

Het verbinden van variabelen werkt twee kanten op, zoals je al gezien hebt. +
`$a := $b` en `$b := $a` hebben hetzelfde effect.

NOTE: Zie https://docs.perl6.org/language/variables voor meer informatie over variabelen.

== Functies en mutators

Het is belangrijk om verschil te maken tussen functies en mutators. +
Functies veranderen de toestand van een object waarop ze worden uitgevoerd *niet*. +
Mutators veranderen de toestand van een object *wel*.

[source,perl6,linenums]
.`Script`
----
my @nummers = [7,2,4,9,11,3];

@nummers.push(99);
say @nummers;      #1

say @nummers.sort; #2
say @nummers;      #3

@nummers.=sort;
say @nummers;      #4
----

.`Output`
----
[7 2 4 9 11 3 99] #1
(2 3 4 7 9 11 99) #2
[7 2 4 9 11 3 99] #3
[2 3 4 7 9 11 99] #4
----

.Uitleg
`.push` is een mutator, het verandert de toestand van het array (#1)

`.sort` is een functie, het geeft het gesorteerde array terug als een lijst, maar verandert de toestand van het array zelf niet.

* (#2) laat zien dat een gesorteerde lijst is teruggegeven.

* (#3) laat zien dat het array zelf onveranderd is.

Men kan een functie als een mutator laten optreden door `.=` in plaats van `.` te gebruiken (#4) (regel 9 van het script)

== Lussen en condities
Perl 6 heeft een veelheid aan conditionele- en lusconstructies.

=== if
De code in het bereik van de conditionele constructie  wordt alleen maar uitgevoerd *indien* de conditie waar (`True`) is.

[source,perl6]
----
my $leeftijd = 19;

if $leeftijd > 18 {
    say 'Welkom'
}
----

In Perl 6 kunnen we de volgorde van de code en de conditie omkeren. +
Maar zelfs als de volgorde is omgekeerd, zal de conditie altijd eerst worden uitgevoerd.

[source,perl6]
----
my $leeftijd = 19;

say 'Welkom' if $leeftijd > 18;
----

We kunnen alternatieve bereiken voor uitvoering aangeven voor het geval dat de conditie niet waar is:

* `else`
* `elsif`

[source,perl6]
----
#voer deze code uit voor verschillende waarden van de variabele
my $aantal-stoelen = 9;

if $aantal-stoelen <= 5 {
    say 'Ik ben een personenauto'
} elsif $aantal-stoelen <= 7 {
    say 'Ik ben een busje'
} else {
    say 'Ik ben een bus'
}
----

=== unless
De tegenovergestelde, ontkennende versie van een if command is `unless` (tenzij).

Deze code:

[source,perl6]
----
my $schone-schoenen = False;

if not $schone-schoenen {
    say 'Maak je schoenen schoon'
}
----
Kan geschreven worden als:

[source,perl6]
----
my $schone-schoenen = False;

unless $schone-schoenen {
    say 'Maak je schoenen schoon'
}
----

Ontkenning (negation) wordt in Perl 6 gedaan met `!` of `not`.

`unless (conditie)` kan worden gebruikt in plaats van `if not (conditie)`.

`unless` kan geen `else` bereik hebben.

=== with

`with` gedraagt zich als een `if` commando, maar kijkt of de variabele een waarde heeft.

[source,perl6]
----
my Int $var=1;

with $var {
    say 'Hallo'
}
----

Als je deze code uitvoert zonder dat je een waarde aan de variabele hebt toegekend, dan zou je geen uitvoer moeten zien.

[source,perl6]
----
my Int $var;

with $var {
    say 'Hallo'
}
----

`without` is de ontkennende versie van `with`.  Net als `unless` van `if`.

Als de eerste `with` niet waar is, dan kan men een alternatief bereik aangeven met `orwith`. +
Je kunt `with` en `orwith` zien als een soort `if` en `elsif`.

=== for

Met het `for` commando kun je over een aantal waarden repeteren.

[source,perl6]
----
my @array = [1,2,3];

for @array -> $array-item {
    say $array-item * 100
}
----

Merk op dat we een lusvariabele `$array-item` aanmaken om de operatie `*100` op elk element van het array uit te kunnen voeren.

=== given

`given` is het Perl 6 equivalent van het `switch` commando in andere programmeertalen.

[source,perl6]
----
my $var = 42;

given $var {
    when 0..50 { say 'Minder dan of gelijk aan 50'}
    when Int { say "is een Int" }
    when 42  { say 42 }
    default  { say "huh?" }
}
----

Het testen van condities stops zodra een conditie van een `when` waar is geweest.

Met `proceed` kun je in Perl 6 aangeven dat je door wilt gaan met testen van condities nadat een conditie waar was.
[source,perl6]
----
my $var = 42;

given $var {
    when 0..50 { say 'Minder dan of gelijk aan 50';proceed}
    when Int { say "is een Int";proceed}
    when 42  { say 42 }
    default  { say "huh?" }
}
----

=== loop

`loop` is een andere manier om een `for` lus aan te geven.

In feite is `loop` precies zoals `for` lussen geschreven worden in de familie C-programmeertalen.

Perl 6 hoort bij de familie C-programmeertalen.

[source,perl6]
----
loop (my $i = 0; $i < 5; $i++) {
    say "Het huidige nummer is $i"
}
----

NOTE: Zie https://docs.perl6.org/language/control voor meer informatie over conditionele- en lusconstructies.

== I/O
De twee meest voorkomende manieren van _Invoer/Uitvoer_ zijn _Terminal_ en _Bestanden_.

=== Basic I/O using the Terminal

==== say
`say` schrijft naar de standaard uitvoer.  Het voegt een regeleinde (newline) toe aan het einde.  In andere woorden, de volgende code:

[source,perl6]
----
say 'Hallo mevrouw.';
say 'Hallo meneer.';
----
zullen op 2 aparte lijnen worden getoond.

==== print
Aan de andere kant doet `print` precies hetzelfde, maar het voegt geen regeleinde toe.

Probeer eens om de `say` door een `print` te vervangen en vergelijk de resultaten.

==== get
Men kan `get` gebruiken om invoer van de terminal te krijgen.

[source,perl6]
----
my $naam;

say "Hoi, hoe heet je?";
$naam = get;

say "Welkom bij Perl 6, beste $naam";
----

Als je bovenstaande code uitvoert zal de terminal wachten tot je je naam intypt en op [Enter] drukt.
Vervolgens zal het je begroeten.

==== prompt
`prompt` is een combinatie van `print` en `get`.

Het bovenstaande voorbeeld kan ook worden geschreven als:

[source,perl6]
----
my $naam = prompt "Hoi, hoe heet je? ";

say "Welkom bij Perl 6, beste $naam";
----

=== Uitvoeren van externe commando's
Deze twee subroutines kunnen worden gebruikt om externe commando's uit te voeren:

* `run` voert een extern commando direct uit.

* `shell` voert een extern commando uit alsof je het hebt ingetypt op een commando regel (via een z.g. "shell").  Het hangt af van de systeem software die je gebruikt.
Alle meta-karakters worden geinterpreteerd door de shell, inclusief z.g. "pipes", "redirects" en specificaties van environment variabelen.

[source,perl6]
.Voer dit uit als je met Linux/OSX werkt
----
my $naam = 'Neo';
run 'echo', "hallo $naam";
shell "ls";
----

[source,perl6]
.Voer dit uit als je met Windows werkt
----
shell "dir";
----
`echo` en `ls` zijn veel voorkomende commando's op Linux/OSX: +
`echo` drukt de argumenten af (het equivalent van `print` in Perl 6) +
`ls` laat alle bestanden en directories zien in de huidige directory

`dir` is het equivalent van `ls` bij Windows.


=== File I/O
==== slurp
Men kan `slurp` gebruiken om een geheel bestand in te lezen.

Maak een tekstbestand aan met de volgende inhoud:

.scores.txt
----
Jan 9
Japie 7
Jolanda 8
Jessica 7
----
[source,perl6]
----
my $data = slurp "scores.txt";
say $data;
----

==== spurt
Men kan `spurt` gebruiken om data naar een bestand te schrijven.

[source,perl6]
----
my $nieuw = "Nieuwe scores:
Paul 10
Paulie 9
Paulo 11";

spurt "nieuwescores.txt", $nieuw;
----

Nadat je de bovenstaande code hebt uitgevoerd, bestaat er een bestand _nieuwescores.txt_ .  Dat zal dan de nieuwe scores bevatten.

=== Werken met bestanden en directories
Perl 6 kan de inhoud van een directory ook direct tonen zonder dat er externe commando's voor hoeven te worden uitgevoerd, net zoals in een van de vorige voorbeelden.

[source,perl6]
----
say dir;              #Laat bestanden/directories uit de huidige directory zien
say dir "/Documents"; #Laat bestanden/directories zien van de gegeven directory
----

Tevens kun je ook nieuwe directories aanmaken en verwijderen.

[source,perl6]
----
mkdir "nieuwdir";
rmdir "nieuwdir";
----

`mkdir` maakt een nieuwe directory aan. +
`rmdir` verwijdert een lege directory.  Returned een foutmelding indien niet leeg.

Je kunt ook kijken of een specifieke naam bestaat, en of het een bestand of een directory is:

Maak in de directory waar je dit script gaat uitvoeren een lege directory `dir123` en een leeg bestand genaamd `script123.pl6`

[source,perl6]
----
say "script123.pl6".IO.e;
say "dir123".IO.e;

say "script123.pl6".IO.d;
say "dir123".IO.d;

say "script123.pl6".IO.f;
say "dir123".IO.f;
----

`IO.e` geeft terug of de naam bestaat. +
`IO.f` geeft terug of het een bestand is. +
`IO.d` geeft terug of het een directory is.

WARNING: Gebruikers van Windows kunnen zowel de `/` als de `\\` gebruiken om directories aan te maken +
`C:\\rakudo\\bin` +
`C:/rakudo/bin` +

NOTE: Zie https://docs.perl6.org/type/IO voor meer informatie over invoer en uitvoer.

== Subroutines
=== Definitie
*Subroutines* (ook wel *subs* of *functies*) zijn een manier om een stuk functionaliteit in een pakketje te stoppen. +

De definitie van een subroutine begint met het sleutelwoord `sub`.  Na de definitie kun je het aanroepen met de naam die je het gegeven hebt. +
Bekijk onderstaand voorbeeld:

[source,perl6]
----
sub buitenaardse-groet {
    say "Hallo aardlingen";
}

buitenaardse-groet;
----

Het vorige voorbeeld laat een subroutine zien die geen invoer nodig heeft.

=== Signatuur
Veel subroutines hebben een vorm van invoer nodig om hun werk te kunnen doen.  Die invoer wordt gegeven door *argumenten*.
Een subroutine mag 0 of meer *parameters* definieren.
Het aantal en het type van de parameters die door een subroutine worden gedefinieerd, noemen we *signatuur*

Onderstaande subroutine accepteert een string argument.

[source,perl6]
----
sub zeg-hallo (Str $naam) {
    say "Hallo " ~ $naam ~ "!!!!"
}
zeg-hallo "Paul";
zeg-hallo "Paula";
----

=== Multiple dispatch
Het is mogelijk om meer dan een subroutine met dezelfde naam, maar met een verschillende signatuur, te definieren.

Op het moment dat de subroutine wordt aangeroepen, zal de uitvoerder besluiten welke versie van de subroutine werkelijk zal worden aangeroepen, afhankelijk van het aantal en het type van de gegeven argumenten.
Dit soort subroutines wordt op dezelfde manier gedefinieerd als normale subroutines, maar in plaats van `sub` worden ze gedefinieerd met `multi`.

[source,perl6]
----
multi groet($naam) {
    say "Good morning $naam";
}
multi groet($naam, $titel) {
    say "Good morning $titel $naam";
}

groet "Jan";
groet "Laura","Mevr.";
----

=== Default end Optionele Parameters
Als een siubroutine is gedefinieerd om een argument te acceptern en we roepen het aan zonder dat benodigde argument, dan zal er een fout optreden.

Als alternatief biedt Perl 6 de mogelijk om subroutines te definieren met:

* Optionele Parameters
* Parameters met een default waarde

Je kunt een optionele parameter aangeven door een `?` achter de naam te plaatsen.

[source,perl6]
----
sub zeg-hallo($naam?) {
    with $naam { say "Hallo " ~ $naam }
    else { say "Hallo Mens" }
}
zeg-hallo;
zeg-hallo("Laura");
----

Als de gebruiker een bepaald argument niet meegeeft, dan wordt de eventuele default waarde van de parameter gebruikt. +
Dit wordt aangegeven door een waarde toe te wijzen aan de parameter in de definitie van de subroutine.

[source,perl6]
----
sub zeg-hallo($naam="Mens") {
    say "Hallo " ~ $naam;
}
zeg-hallo;
zeg-hallo("Laura");
----

=== Teruggeven van waarden
Alle subroutines die we tot nu toe hebben gezien *doen iets* en laten dan het resultaat op het scherm zien.

Ook al is dit heel normaal, soms willen we dat een subroutine een waarde *teruggeeft* dat we later in het programma kunnen gebruiken.

Onder normal omstandigheden is de waarde van de laatste regel van een subroutine de waarde die door de subroutine terug wordt gegeven.
[source,perl6]
.Impliciet teruggeven
----
sub kwadrateer ($x) {
    $x ** 2;
}
say "7 gekwadrateerd is gelijk aan " ~ kwadrateer(7);
----

Zodra je programma groter wordt, is het wellicht een goed idee om _expliciet_ aan te geven wat we terug willen geven.
Dit kunnen we doen met het `return` sleutelwoord.
[source,perl6]
.Expliciete teruggave
----
sub kwadrateer ($x) {
    return $x ** 2;
}
say "7 gekwadrateerd is gelijk aan " ~ kwadrateer(7);
----
==== Beperken van mogelijke teruggegeven waarden
In een van de vorige voorbeelden hebben we gezien dat we parameters kunnen beperken tot een bepaald type.
Hetzelfde kan worden gedaan met waarden die we teruggeven.

Om de teruggeven waarde te beperken tot een bepaald type kunnen we of de `returns` eigenschap gebruiken, of de pijlnotatie `-\->` in de signatuur gebruiken.

[source,perl6]
.Gebruik van de returns eigenschap
----
sub kwadrateer ($x) returns Int {
    return $x ** 2;
}
say "1.2 gekwadrateerd is gelijk aan " ~ kwadrateer(1.2);
----

[source,perl6]
.Gebruik van de pijlnotatie
----
sub kwadrateer ($x --> Int) {
    return $x ** 2;
}
say "1.2 gekwadrateerd is gelijk aan " ~ kwadrateer(1.2);
----
Als we niet een waarde voor teruggave van het juiste type aangeven, zal er een foutmelding worden geproduceerd.

----
Type check failed for return value; expected Int but got Rat (1.44)
----

[TIP]
====
We kunnen niet alleen de typebeperking van de teruggeven waarde controleren; we kunnen ook laten controleren of het gedefinieerd is.

In het vorige voorbeeld gaven we aan dat de teruggegeven waarde een `Int` most zijn, zonder iets te zeggen over het wel of niet gedefinieerd zijn.
We zouden ook hebben kunnen aangeven dat de teruggegeven `Int` wel of niet gedefinieerd moet zijn, met de volgende signaturen: +
`--> Int:D` en `--> Int:U`

Het is een goede gewoonte om dit soort typebeperkingen te gebruiken. +
Hieronder is een aangepaste versie van het vorige voorbeeld die `:D` gebruikt om aan te geven dat de teruggegeven `Int` gedefinieerd moet zijn.

[source,perl6]
----
sub kwadrateer ($x --> Int:D) {
    return $x ** 2;
}
say "1.2 gekwadrateerd is gelijk aan " ~ kwadrateer(1.2);
----
====

NOTE: Zie https://docs.perl6.org/language/functions voor meer informatie over subroutines en functies.

== Functioneel Programmeren
In dit hoofdstuk gaan we kijken naar een aantal functionaliteiten die men kan gebruiken voor Functioneel Programmeren.

=== Functies zijn ook objecten.
Functies en subroutines zijn ook objecten, net als alle andere:

* Ze kunnen worden doorgegeven als argument aan een subroutine

* Ze kunnen worden teruggegeven als waarde door een subroutine

* Ze kunnen worden toegekend aan een variabele

Een prachtig voorbeeld om dit concept te demonstreren is de `map` functie. +
`map` is een zogenaamde *hogere orde functie*, want het accepteert een andere functie als argument.

[source,perl6]
.Script
----
my @array = <1 2 3 4 5>;
sub kwadrateer($x) {
    $x ** 2
}
say map(&kwadrateer,@array);
----

.Uitvoer
----
(1 4 9 16 25)
----

.Uitleg
We hebben een subroutine `kwadrateer` gedefinieerd die het argument tot de tweede macht verheft. +
Vervolgens hebben we `map` aangeroepen met twee argumenten: een subroutine en een array. +
Het resultaat is dat alle elementen van het array zijn gekwadrateerd.

Merk op dat als we een subroutine als argument willen doorgeven, we een `&` voor de naam moeten zetten.

=== Closure
Alle code objecten in Perl 6 zijn zogenaamde `closures`, hetgeen betekent dat ze kunnen refereren aan lokale variabelen die zichtbaar zijn buiten het directe eigen bereik.

=== Anonieme Functies
Een *anonieme functie* wordt ook wel een *lambda* genoemd. +
Een anonieme functie is niet bekend onder een naam (want die heeft het niet).

Laten we het `map` voorbeeld herschrijven met een anonieme functie
[source,perl6]
----
my @array = <1 2 3 4 5>;
say map(-> $x {$x ** 2},@array);
----
Merk op dat in plaats van een subroutine te declareren en het door middel van de naam als argument aan `map` door te geven, we het direct in de aanroep definieren. +
De anonieme subroutine `\-> $x { $x ** 2 }` can niet als zodanig worden aangeroepen want het heeft geen naam.

In Perl 6 noemen we deze notatie een *pointy block*

[source,perl6]
.Een pointy block kan ook aan een variabele worden toegekend:
----
my $kwadrateer = -> $x {
    $x ** 2
}
say $kwadrateer(9);
----

=== Aankoppelen
In Perl 6 kun je methoden aan elkaar koppelen, zodat je niet langer het resultaat van de aanroep van de ene subroutine als een argument aan een andere hoeft te geven.

Laten we het geval bekijken waarbij we een array met waarden kregen.
Je wordt gevraagd om alle unieke (maar een keer voorkomende) waarden uit het array te halen en te sorteren van hoog naar laag.

Je zou dit probleem kunnen oplossen door iets te schrijven als:
[source,perl6]
----
my @array = <7 8 9 0 1 2 4 3 5 6 7 8 9>;
my @resultaat = reverse(sort(unique(@array)));
say @resultaat;
----
Eerst roepen we de `unique` functie aan op `@array`.  Het resultaat daarvan geven we als argument aan `sort` en dan geven we het resultaat daarvan door aan `reverse`.

In tegenstelling tot bovenstaand voorbeeld mag je methodes aan elkaar koppelen in Perl 6. +
Bovenstaand voorbeeld kan dus als volgt worden geschreven, waarbij we gebruik maken van het *aankoppelen van methoden* (method chaining):

[source,perl6]
----
my @array = <7 8 9 0 1 2 4 3 5 6 7 8 9>;
my @resultaat = @array.unique.sort.reverse;
say @resultaat;
----

Je kunt zien dat het aankoppelen van methoden _veel beter leest_.

=== Aanvoer Operator
De *aanvoer operator*, ook wel _pipe_ genoemd in sommige functioneel programmeertalen, geeft een nog beter visualisatie van het aankoppelen van methoden.
[source,perl6]
.Voorwaardse Aanvoer
----
my @array = <7 8 9 0 1 2 4 3 5 6 7 8 9>;
@array ==> unique()
       ==> sort()
       ==> reverse()
       ==> my @resultaat;
say @resultaat;
----

.Uitleg
----
Start met `array` en geef een lijst van unieke elementen
                  en sorteer dat
                  en keer de volgorde om
                  en sla het resultaat daarvan op in @resultaat
----
Zoals je kunt zien is de volgorde van de aanroepen van de methoden van voor naar achter.


[source,perl6]
.Achterwaardse Aanvoer
----
my @array = <7 8 9 0 1 2 4 3 5 6 7 8 9>;
my @resultaat <== reverse()
              <== sort()
              <== unique()
              <== @array;
say @resultaat;
----

.Uitleg
De achterwaardse aanvoer is net als de voorwaardse aanvoer, maar dan andersom. +
De volgorde van de aanroepen van de methoden is van achteren naar voren.

=== Hyper Operator
De *hyper operator* `>>.` roept de methode aan op elke element van een lijst en geeft een lijst terug met het resultaat van die aanroepen.
[source,perl6]
----
my @array = <0 1 2 3 4 5 6 7 8 9 10>;
sub is-even($var) { $var %% 2 };

say @array>>.is-prime;
say @array>>.&is-even;
----

Met de hyper operator kunnen we methoden aanroepen die standaar al in Perl 6 zijn gedefinieerd, zoals `is-prime` dat ons vertelt of een getal een priemgetal is of niet. +
Daarnaast kun je nieuwe subroutines definieren en ze aanroepen met de hyper operator.  In dat geval moeten we een `&` voor de naam plaatsen, bijvoorbeeld `is-even`

Dit is erg practisch want daardoor hoeven we geen `for` lus te schrijven om over elk element te itereren.

WARNING: Perl 6 garandeert dat de volgorde van de resultaten hetzelfde is als de volgorde van de originele waarden. +
Maar er is *geen garantie* dat Perl 6 de methoden in de zelfde volgorde of in dezelfde thread zal uitvoeren. +
Men moet dus voorzichtig zijn bij het aanroepen van methoden met neveneffecten, zoals `say` (waarbij het neveneffect het tonen van de waarden is).

=== Juncties
Een *junctie* is een logische superpositie van waarden.

In onderstaand voorbeeld is `1|2|3` een junctie.
[source,perl6]
----
my $var = 2;
if $var == 1|2|3 {
    say "De variabele is 1 of 2 of 3"
}
----
Het gebruik van juncties zorgt meestal voor zogenaamde *autothreading*;
een opdracht wordt voor elk element van de junctie uitgevoerd en de resultaten daarvan worden in een nieuwe junctie opgeslagen en teruggegeven.

=== Luie Lijsten
Een *luie lijst* is een lijst die lamlendig wordt geevalueerd. +
Lamlendig evalueren stelt de evaluatie van een expressie uit totdat deze echt nodig is en probeert herhaalde evaluaties te voorkomen door resultaten op te slaan.

De voordelen zijn:

* Verbeterde prestaties doordat onnodige berekening worden vermeden

* De mogelijkheid om potentieel oneindige datastructuren aan te maken

* De mogelijkheid om de besturingsstroom te definieren

Om een luie lijst te maken gebruiken we de `...` infix operator. +
Een luie lijst heeft een of meer *startelementen*, een *generator* en een *eindpunt*.

[source,perl6]
.Simpele luie lijst
----
my $luielijst = (1 ... 10);
say $luielijst;
----
Het start element is 1 en het eindpunt is 10.  Er is geen generator aangegeven, dus de default generator wordt gebruikt (+1). +
In andere woorden, deze luie lijst zal de volgende waarden teruggeven (indien daarom wordt gevraagd): (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

[source,perl6]
.Oneindige luie lijst
----
my $luielijst = (1 ... Inf);
say $luielijst;
----
Deze luie lijst kan een getal tussen 1 en oneindig geven, in andere woorden alle natuurlijke getallen.

[source,perl6]
.Luie lijst met een afgeleide generator
----
my $luielijst = (0,2 ... 10);
say $luielijst;
----
The startelementen zijn 0 en 2 en het eindpunt is 10.
Er is geen generator aangegeven, maar door de aangegeven startelementen kan Perl 6 deduceren dat de generator (+2) is +
Deze luie lijst zal de volgende waarden teruggeven (indien daarom wordt gevraagd): (0, 2, 4, 6, 8, 10)

[source,perl6]
.Luie lijst met een specifieke generator
----
my $luielijst = (0, { $_ + 3 } ... 12);
say $luielijst;
----
In dit voorbeeld specificeren we expliciet een generator tussen `{ }` +
Deze luie lijst zal de volgende waarden teruggeven (indien daarom wordt gevraagd): (0, 3, 6, 9, 12)

[WARNING]
====
Indien men een expliciete generator specificeert moet het eindpunt een van de waarden zijn die door de generator terug kan worden gegeven. +
Als we in bovenstaand voorbeeld het eindpunt vervangen door 10 in plaats van 12, dan zal de generator nooit stoppen.
De generator springt dan _over_ het eindpunt.

In plaats van `0 ...^ * > 10` kun je ook `0 ... 10` schrijven +
Je kunt dat lezen als: vanaf 0 tot de eerste waarde die groter is dan 10 (maar sluit die dan uit)
[source,perl6]
.Deze generator zal nooit stoppen
----
my $luielijst = (0, { $_ + 3 } ... 10);
say $luielijst;
----

[source,perl6]
.Deze generator zal wel stoppen
----
my $luielijst = (0, { $_ + 3 } ...^ * > 10);
say $luielijst;
----
====

== Klassen en Objecten
In het vorige hoofdstuk hebben we geleerd hoe Perl 6 het gemakkelijker maakt om Functioneel te Programmeren. +
In dit hoofdstuk gaan we kijken naar het object georienteerd programmeren in Perl 6.

=== Inleiding

_Object Georienteerd_ Programmeren is een van de programmeerstijl paradigma's die tegenwoordig veel wordt gebruikt. +
Een *object* is een verzameling van variabelen en subroutines die bij elkaar gevoegd zijn. +
De variabelen noemen we *attributen* en de subroutines noemen we *methoden*. +
Attributen bepalen de *staat* van een object, methoden bepalen het *gedrag* van het object.

Een *klasse* definieert de structuur van een verzameling *objecten*. +

Bijkijk onderstaand voorbeeld om deze relatie beter te begrijpen:

|===

| Er bevinden zich 4 personen in een kamer | *objecten* => 4 personen

| Deze 4 personen zijn menselijk | *klasse* => Mens

| Ze hebben een allen een naam, leeftijd, geslacht en nationaliteit | *attributen* => naam, leeftijd, geslacht en nationaliteit

|===

In het taalgebruik van _object georienteerd_ programmeren zeggen we dat de objecten *instanties* zijn van een klasse.

Bekijk het onderstaande script:
[source,perl6]
----
class Mens {
    has $naam;
    has $leeftijd;
    has $geslacht;
    has $nationaliteit;
}

my $jan = Mens.new(naam => 'Jan', leeftijd => 23, sex => 'M', nationaliteit => 'Nederlands');
say $jan;
----
Met het `class` sleutelwoord definieert men een klasse. +
Met het `has` sleutelwoord definieert men een attribuut van een klasse. +
De `.new()` methode wordt een *constructeur* genoemd.  Het maakt een object als een instantie van de klasse waarop het wordt aangeroepen.

In het bovenstaande script, bevat de variabele `$jan` de nieuwe instantie van "Mens" aangemaakt met `Mens.new()`. +
De argumenten op naam die we aan de `.new()` methode meegeven, worden gebruikt om de attributen van het nieuwe object te initialiseren.

We kunnen een klasse ook een _lexicaal gebied_ geven door middel van `my`:
[source,perl6]
----
my class Mens {

}
----

=== Inkapseling
Inkapseling is een concept uit het object georienteerd programmeren waarmee we de bundeling van data en methoden aangeven. +
De gegevens (attributen) binnen een object zouden *prive* moeten zijn.  In andere woorden, alleen maar toegankelijk vanaf binnen in het object. +
Om toegang te verlenen aan de attributen vanaf buiten het object, gebruiken we methoden die we *accessors* noemen.

Onderstaande scripts geven hetzelfde resultaat.

.Directe toegang tot een variabele
[source,perl6]
----
my $var = 7;
say $var;
----

.Inkapseling
[source,perl6]
----
my $var = 7;
sub geef-var {
    $var;
}
say geef-var;
----
De subroutine `geef-var` kan men als een accessor beschouwen.  Het maakt het mogelijk om aan de waarde van de variabele te komen zonder er direct toegang daarvoor nodig te hebben.

Inkapseling wordt in Perl 6 mogelijk gemaakt door middel van zogenaamde *twigils*. +
Twigils zijn secondaire _sigils_.  Ze worden tussen de sigil en de naam van het attribuut geplaatst. +
Bij klassen kunnen twee sigils worden gebruikt:

* `!` om aan te geven dat een attribuut prive is.
* `.` om aan te geven dat een accessor voor de attribuut aangemaakt moet worden.

Als men geen twigil meegeeft, is een attribuut prive.  Voor de leesbaarheid is het een goede gewoonte om in zo'n geval altijd de `!` twigil te gebruiken.

Met wat we zojuist gezien hebben, zouden we bovenstaande klasse moeten herschrijven als:
[source,perl6]
----
class Mens {
    has $!naam;
    has $!leeftijd;
    has $!geslacht;
    has $!nationaliteit;
}

my $jan = Mens.new(naam => 'Jan', leeftijd => 23, sex => 'M', nationaliteit => 'Nederlands');
say $jan;
----
Voeg het volgende commando to: `say $jan.leeftijd` +
Het zal de volgende fout geven: `Method 'leeftijd' not found for invocant of class 'Mens'` +
De reden hiervoor is dat `$!leeftijd` prive is en daardoor alleen maar binnen het object gebruikt kan worden.
Pogingen om aan het attribuut te komen van buiten het object zal je een foutmelding geven.

Vervang nu `has $!leeftijd` with `has $.leeftijd` en bekijk dan het resultaat van `say $jan.leeftijd;`

=== Argumenten op naam vs. argumenten op positie
Alle klassen hebben beschikking over een `.new()` constructor` door overerving. +
Het kan worden gebruikt om objecten aan te maken door het argumenten te geven. +
De default constructeur accepteert alleen *argumentn op naam*. +
Als je bovenstaande voorbeelden bekijkt, dan zul je zien dat alle argumenten die we aan `.new()` hebben gegeven, op naam zijn:

* naam => 'Jan'

* leeftijd => 23

Wat indien ik niet telkens de naam van elk attribuut wil meegeven als ik een nieuw object wil maken? +
In dat geval moeten we een andere constructeur maken die *argumenten op positie* accepteert.

[source,perl6]
----
class Mens {
    has $.naam;
    has $.leeftijd;
    has $.geslacht;
    has $.nationaliteit;
    #nieuwe constructeur die de default constructeur vervangt voor deze klasse
    method new ($naam,$leeftijd,$geslacht,$nationaliteit) {
        self.bless(:$naam,:$leeftijd,:$geslacht,:$nationaliteit);
    }
}

my $jan = Human.new('Jan',23,'M','Nederlands');
say $jan;
----

=== Methoden

==== Inleiding
Methoden zijn de _subroutines_ van een object. +
Net als subroutines
Like subroutines, they are a means of packaging a set of functionality, they accept *arguments*, have a *signature* and can be defined as *multi*.

Methods are defined using the `method` keyword. +
In normal circumstances, methods are required to perform some sort of action on the objects' attributes.
This enforces the concept of encapsulation. Object attributes can only be manipulated from within the object using methods.
The outside world, can only interact with the object methods, and has no access to its attributes.

[source,perl6]
----
class Mens {
    has $.naam;
    has $.leeftijd;
    has $.geslacht;
    has $.nationaliteit;
    has $.geschiktheid;
    method bepaal-geschiktheid
        if self.leeftijd < 21 {
            $!geschiktheid = 'Nee'
        } else {
            $!geschiktheid = 'Ja'
        }
    }
}

my $jan = Mens.new(naam => 'Jan', leeftijd => 23, geslacht => 'M', nationaliteit => 'Nederlands');
$jan.bepaal-geschiktheid;
say $jan.geschiktheid;
----

Door een methode te definieren in een klasse, kun je deze aanroepen op een object met de _punt notatie_: +
_object_ *.* _methode_ of als in bovenstaand voorbeeld: `$jan.bepaal-geschiktheid`

Binnen de definitie van een methode kunnen we het sleutelwoord `self` gebruiken om te refereren aan het object zelf om een andere methode aan te roepen. +

Binnen de definitie van een methode kunnen we direct een attribuut gebruiken door de `!` twigil te gebruiken, zelfs als het attribuut is gedefinieerd met de `.` twigil. +
De reden daarachter is dat wat de `.` twigil doet is een attribuut met `!` te definieren en automatisch te zorgen voor het aanmaken van een accessor.

In bovenstaand voorbeeld hebben `if self.leeftijd < 21` en `if $!leeftijd < 21` hetzelfde effect, maar technisch gezien zijn ze verschillend:

* `self.leeftijd` roept de `.leeftijd` methode (accessor) aan +
Hetgeen overigens ook geschreven can worden als `$.leeftijd`
* `$!leeftijd` is een directe toegang tot de variabele

==== Prive methoden
Normale methoden kunnen op objecten buiten de klasse zelf worden aangeroepen.

*Prive methoden* zijn methoden die alleen maar kunnen worden aangeroepen binnen een klasse. +
Dit kan bijvoorbeeld gebruikt worden als een methode een andere methode moet aanroepen voor een specifieke actie.
De methode die gebruikt kan worden vanaf de buitenwereld is publiek, terwijl de andere methode onzichtbaar moet blijven.
Aangezien we niet willen dat gebruikers die methode direct kunnen aanroepen, definieren we het als een prive methode.

Door een `!` voor de naam van een methode te plaatsen, geven we aan dat het om een prive methode gaat.
Prive methoden moeten worden aangeroepen met een `!` in plaats van met `.`

[source,perl6]
----
method !ikbenprive {
    #code waar het over gaat
}

method ikbenprive {
  self!ikbenprive;
  #doe extra dingen
}
----

=== Klasse Attributen

*Klasse Attributen* zijn attributen die bij de klasse zelf horen en niet bij de objecten van die klasse. +
Zij kunnen worden geinitialiseerd bij de definitie. +
Klasse attributen worden gedefinieerd met `my` in plaats van met `has`. +
Zij worden aangeroepen op de klasse zelf in plaats van op haar objecten.

[source,perl6]
----
class Mens {
    has $.naam;
    my $.aantal = 0;
    method new($naam) {
        Mens.aantal++;
        self.bless(:$naam);
    }
}
my $a = Mens.new('a');
my $b = Mens.new('b');

say Mens.aantal;
----

=== Toegangssoorten
In alle voorbeelden die we tot nu toe hebben gezien, hebben we accessors alleen maar gebruikt om informatie uit een object te halen.

Maar wat nu als we de waarde van een attribuut willen veranderen? +
In dat geval moeten we die attribuut als _lees/schrijf_ markeren met de sleutelwoorden `is rw` (read/write)
[source,perl6]
----
class Mens {
    has $.naam;
    has $.leeftijd is rw;
}
my $jan = Mens.new(naam => 'Jann', leeftijd => 21);
say $jan.leeftijd;

$jan.leeftijd = 23;
say $jan.leeftijd;
----
Als je bij de definitie niets aangeeft, wordt een attribuut als _alleen lezen_ gedefinieerd, maar je kunt ook expliciet `is readonly` aangeven

=== Inheritance
==== Inleiding
*Inheritance* is another concept of object oriented programming.

When defining classes, soon enough we will realize that some attributes/methods are common to many classes. +
Should we duplicate code? +
NO! We should use *inheritance*

Let's consider we want to define two classes, a class for Human beings and a class for Employees. +
Human beings have 2 attributes: name and age. +
Employees have 4 attributes: name, age, company and salary

One would be tempted to define the classes as follow:
[source,perl6]
----
class Human {
  has $.name;
  has $.age;
}

class Employee {
  has $.name;
  has $.age;
  has $.company;
  has $.salary;
}
----
While technically correct the above piece of code is considered conceptually poor.

A better way to write it would be as follow:
[source,perl6]
----
class Human {
  has $.name;
  has $.age;
}

class Employee is Human {
  has $.company;
  has $.salary;
}
----
The `is` keyword defines inheritance. +
In object oriented parlance we say Employee is a *child* of Human, and Human is a *parent* of Employee.

All child classes inherit the attributes and methods of the parent class, so there is no need to redefine them.

==== Overriding
Classes inherit all attributes and methods from their parent classes. +
There are cases where we need the method in the child class to behave differently than the one inherited. +
To achieve this, we redefine the method in the child class. +
This concept is called *overriding*.

In the below example, the method `introduce-yourself` is inherited by the Employee class.

[source,perl6]
----
class Human {
  has $.name;
  has $.age;
  method introduce-yourself {
    say 'Hi i am a human being, my name is ' ~ self.name;
  }
}

class Employee is Human {
  has $.company;
  has $.salary;
}

my $john = Human.new(name =>'John', age => 23,);
my $jane = Employee.new(name =>'Jane', age => 25, company => 'Acme', salary => 4000);

$john.introduce-yourself;
$jane.introduce-yourself;
----
Overriding works as follow:

[source,perl6]
----
class Human {
  has $.name;
  has $.age;
  method introduce-yourself {
    say 'Hi i am a human being, my name is ' ~ self.name;
  }
}

class Employee is Human {
  has $.company;
  has $.salary;
  method introduce-yourself {
    say 'Hi i am a employee, my name is ' ~ self.name ~ ' and I work at: ' ~ self.company;
  }

}

my $john = Human.new(name =>'John',age => 23,);
my $jane = Employee.new(name =>'Jane',age => 25,company => 'Acme',salary => 4000);

$john.introduce-yourself;
$jane.introduce-yourself;
----

Depending of which class the object is, the right method will be called.

==== Submethods
*Submethods* are a type of method that are not inherited by child classes. +
They are only accessible from the class they were declared in. +
They are defined using the `submethod` keyword.

=== Multiple Inheritance
Multiple inheritance is allowed in Perl 6. A class can inherit from multiple other classes.

[source,perl6]
----
class bar-chart {
  has Int @.bar-values;
  method plot {
    say @.bar-values;
  }
}

class line-chart {
  has Int @.line-values;
  method plot {
    say @.line-values;
  }
}

class combo-chart is bar-chart is line-chart {
}

my $actual-sales = bar-chart.new(bar-values => [10,9,11,8,7,10]);
my $forecast-sales = line-chart.new(line-values => [9,8,10,7,6,9]);

my $actual-vs-forecast = combo-chart.new(bar-values => [10,9,11,8,7,10],
                                         line-values => [9,8,10,7,6,9]);
say "Actual sales:";
$actual-sales.plot;
say "Forecast sales:";
$forecast-sales.plot;
say "Actual vs Forecast:";
$actual-vs-forecast.plot;
----

.`Output`
----
Actual sales:
[10 9 11 8 7 10]
Forecast sales:
[9 8 10 7 6 9]
Actual vs Forecast:
[10 9 11 8 7 10]
----

.Explanation
The `combo-chart` class should be able to hold two series, one for the actual values plotted on bars,
and another for forecast values plotted on a line. +
This is why we defined it as a child of `line-chart` and `bar-chart`. +
You should have noticed that calling the method `plot` on the `combo-chart` didn't yield the required result.
Only one series was plotted. +
Why did this happen? +
`combo-chart` inherits from `line-chart` and `bar-chart`, and both of them have a method called `plot`.
When we call that method on `combo-chart` Perl 6 internals will try to resolve the conflict by calling one of the inherited methods.

.Correction
In order to behave correctly, we should have overridden the method `plot` in the `combo-chart`.

[source,perl6]
----
class bar-chart {
  has Int @.bar-values;
  method plot {
    say @.bar-values;
  }
}

class line-chart {
  has Int @.line-values;
  method plot {
    say @.line-values;
  }
}

class combo-chart is bar-chart is line-chart {
  method plot {
    say @.bar-values;
    say @.line-values;
  }
}

my $actual-sales = bar-chart.new(bar-values => [10,9,11,8,7,10]);
my $forecast-sales = line-chart.new(line-values => [9,8,10,7,6,9]);

my $actual-vs-forecast = combo-chart.new(bar-values => [10,9,11,8,7,10],
                                         line-values => [9,8,10,7,6,9]);
say "Actual sales:";
$actual-sales.plot;
say "Forecast sales:";
$forecast-sales.plot;
say "Actual vs Forecast:";
$actual-vs-forecast.plot;
----

.`Output`
----
Actual sales:
[10 9 11 8 7 10]
Forecast sales:
[9 8 10 7 6 9]
Actual vs Forecast:
[10 9 11 8 7 10]
[9 8 10 7 6 9]
----

=== Roles
*Roles* are somehow similar to classes in the sense that they are a collection of attributes and methods.

Roles are declared with the keyword `role` and classes that wish to implement the role can do so using the `does` keyword.

.Lets rewrite the multiple inheritance example using roles:
[source,perl6]
----
role bar-chart {
  has Int @.bar-values;
  method plot {
    say @.bar-values;
  }
}

role line-chart {
  has Int @.line-values;
  method plot {
    say @.line-values;
  }
}

class combo-chart does bar-chart does line-chart {
  method plot {
    say @.bar-values;
    say @.line-values;
  }
}

my $actual-sales = bar-chart.new(bar-values => [10,9,11,8,7,10]);
my $forecast-sales = line-chart.new(line-values => [9,8,10,7,6,9]);

my $actual-vs-forecast = combo-chart.new(bar-values => [10,9,11,8,7,10],
                                         line-values => [9,8,10,7,6,9]);
say "Actual sales:";
$actual-sales.plot;
say "Forecast sales:";
$forecast-sales.plot;
say "Actual vs Forecast:";
$actual-vs-forecast.plot;
----

Run the above script and you will see that results are the same.

By now you're asking yourself; if roles behave like classes what's their use? +
To answer your question modify the first script used to showcase multiple inheritance,
the one where we _forgot_ to override the `plot` method.

[source,perl6]
----
role bar-chart {
  has Int @.bar-values;
  method plot {
    say @.bar-values;
  }
}

role line-chart {
  has Int @.line-values;
  method plot {
    say @.line-values;
  }
}

class combo-chart does bar-chart does line-chart {
}

my $actual-sales = bar-chart.new(bar-values => [10,9,11,8,7,10]);
my $forecast-sales = line-chart.new(line-values => [9,8,10,7,6,9]);

my $actual-vs-forecast = combo-chart.new(bar-values => [10,9,11,8,7,10],
                                         line-values => [9,8,10,7,6,9]);
say "Actual sales:";
$actual-sales.plot;
say "Forecast sales:";
$forecast-sales.plot;
say "Actual vs Forecast:";
$actual-vs-forecast.plot;
----

.`Output`
----
===SORRY!===
Method 'plot' must be resolved by class combo-chart because it exists in multiple roles (line-chart, bar-chart)
----

.Explanation
If multiple roles are applied to the same class, and a conflict arises, a compile-time error will be thrown. +
This is a much safer approach than multiple inheritance where conflicts are not considered errors and are simply resolved at runtime.

Roles will warn you that there's a conflict.

=== Introspection
*Introspection* is the process of getting information about an object properties like its type, or its attributes or its methods.

[source,perl6]
----
class Human {
  has Str $.name;
  has Int $.age;
  method introduce-yourself {
    say 'Hi i am a human being, my name is ' ~ self.name;
  }
}

class Employee is Human {
  has Str $.company;
  has Int $.salary;
  method introduce-yourself {
    say 'Hi i am a employee, my name is ' ~ self.name ~ ' and I work at: ' ~ self.company;
  }
}

my $john = Human.new(name =>'John',age => 23,);
my $jane = Employee.new(name =>'Jane',age => 25,company => 'Acme',salary => 4000);

say $john.WHAT;
say $jane.WHAT;
say $john.^attributes;
say $jane.^attributes;
say $john.^methods;
say $jane.^methods;
say $jane.^parents;
if $jane ~~ Human {say 'Jane is a Human'};
----
Introspection is facilitated by:

* `.WHAT` returns the class from which the object has been created.

* `.^attributes` returns a list containing all attributes of the objects.

* `.^methods` returns all methods that can be called on the object.

* `.^parents` returns all parent classes of the class the object belongs.

* `~~` is called the smart-match operator.
It evaluates to _True_ if the object is created from the class it is being compared against or any of its inheritances.

[NOTE]
--
For more info on Object Oriented Programming in Perl 6, see:

* https://docs.perl6.org/language/classtut
* https://docs.perl6.org/language/objects
--
== Exception Handling

=== Catching Exceptions
*Exceptions* are a special behavior that happens at runtime when something goes wrong. +
We say that exceptions are _thrown_.

Consider the below script that runs correctly:

[source,perl6]
----
my Str $name;
$name = "Joanna";
say "Hello " ~ $name;
say "How are you doing today?"
----

.`Output`
----
Hello Joanna
How are you doing today?
----

Now consider this script that throws an exception:

[source,perl6]
----
my Str $name;
$name = 123;
say "Hello " ~ $name;
say "How are you doing today?"
----

.`Output`
----
Type check failed in assignment to $name; expected Str but got Int
   in block <unit> at exceptions.pl6:2
----

You should have remarked that whenever an error occurs (in this case assigning a number to a string variable) the program will stop and other lines of code will not be evaluated, even if correct.

*Exception handling* is the process of _catching_ an exception that has been _thrown_ in order for the script to continue working.

[source,perl6]
----
my Str $name;
try {
  $name = 123;
  say "Hello " ~ $name;
  CATCH {
    default {
      say "Can you tell us your name again, we couldn't find it in the register.";
    }
  }
}
say "How are you doing today?";
----

.`Output`
----
Can you tell us your name again, we couldn't find it in the register.
How are you doing today?
----

Exception handling is done by using a `try-catch` block.

[source,perl6]
----
try {
  #code goes in here
  #if anything goes wrong, the script will enter the below CATCH block
  #if nothing goes wrong the CATCH block will be ignored
  CATCH {
    default {
      #the code in here will be evaluated only if an exception has been thrown
    }
  }
}
----

The `CATCH` block can be defined the same way a `given` block is defined.
This means we can _catch_ and handle differently many types of exceptions.

[source,perl6]
----
try {
  #code goes in here
  #if anything goes wrong, the script will enter the below CATCH block
  #if nothing goes wrong the CATCH block will be ignored
  CATCH {
    when X::AdHoc { #do something if an exception of type X::AdHoc is thrown }
    when X::IO { #do something if an exception of type X::IO is thrown }
    when X::OS { #do something if an exception of type X::OS is thrown }
    default { #do something if an exception is thrown and doesn't belong to the above types }
  }
}
----

=== Throwing Exceptions
In contrast to catching exceptions, Perl 6 also allows you to explicitly throw exceptions. +
Two types of exceptions can be thrown:

* ad-hoc exceptions

* typed exceptions

[source,perl6]
.ad-hoc
----
my Int $age = 21;
die "Error !";
----

[source,perl6]
.typed
----
my Int $age = 21;
X::AdHoc.new(payload => 'Error !').throw;
----

Ad-hoc exceptions are thrown using the `die` subroutine followed by the exception message.

Typed exceptions are objects, hence the use of the `.new()` constructor in the above example. +
All typed exceptions descend from class `X` , below are a few examples: +
`X::AdHoc` is the simplest exception type +
`X::IO` is related to IO errors +
`X::OS` is related to OS errors +
`X::Str::Numeric` related to trying to coerce a string to a number

NOTE: For a complete list of exception types and their associated methods go to https://docs.perl6.org/type-exceptions.html


== Regular Expressions
A regular expression, or _regex_ is a sequence of characters that is used for pattern matching. +
The easiest way to understand it is to think of it as a pattern.

[source,perl6]
----
if 'enlightenment' ~~ m/ light / {
    say "enlightenment contains the word light";
}
----

In this example, the smart match operator `~~` is used to check if a string (enlightenment) contains the word (light). +
"Enlightenment" is matched against a regex `m/ light /`

=== Regex definition

A regular expression can be defined as follows:

* `/light/`

* `m/light/`

* `rx/light/`

Unless specified explicitly, white space is irrelevant, `m/light/` and `m/ light /` are the same.

=== Matching characters
Alphanumeric characters and the underscore `_` are written as is. +
All other characters have to be escaped using a backslash or surrounded by quotes.

[source,perl6]
.Backslash
----
if 'Temperature: 13' ~~ m/ \: / {
    say "The string provided contains a colon :";
}
----

[source,perl6]
.Single quotes
----
if 'Age = 13' ~~ m/ '=' / {
    say "The string provided contains an equal character = ";
}
----

[source,perl6]
.Double quotes
----
if 'name@company.com' ~~ m/ "@" / {
    say "This is a valid email address because it contains an @ character";
}
----

=== Matching categories of characters
Characters can be classified into categories and we can match against them. +
We can also match against the inverse of that category (everything except it):

|===

| *Category* | *Regex* | *Inverse* | *Regex*

| Word character (letter, digit or underscore) | \w | Any character except a word character | \W

| Digit | \d | Any character except a digit | \D

| Whitespace | \s | Any character except a whitespace | \S

| Horizontal whitespace | \h | Any character except a horizontal whitespace | \H

| Vertical whitespace | \v | Any character except a vertical whitespace | \V

| Tab | \t | Any character except a Tab | \T

| New line | \n | Any character except a new line | \N

|===

[source,perl6]
----
if "John123" ~~ / \d / {
  say "This is not a valid name, numbers are not allowed";
} else {
  say "This is a valid name"
}
if "John-Doe" ~~ / \s / {
  say "This string contains whitespace";
} else {
  say "This string doesn't contain whitespace"
}
----

=== Unicode properties
Matching against categories of characters as seen in the preceding section is convenient. +
That being said, a more systematic approach would be to use of Unicode properties. +
Unicode properties are enclosed in `<: >`

[source,perl6]
----
if "John123" ~~ / <:N> / {
  say "Contains a number";
} else {
  say "Doesn't contain a number"
}
if "John-Doe" ~~ / <:Lu> / {
  say "Contains an uppercase letter";
} else {
  say "Doesn't contain an upper case letter"
}
if "John-Doe" ~~ / <:Pd> / {
  say "Contains a dash";
} else {
  say "Doesn't contain a dash"
}
----

=== Wildcards
Wildcards can also be used in a regex.

The dot `.` means any single character.

[source,perl6]
----
if 'abc' ~~ m/ a.c / {
    say "Match";
}
if 'a2c' ~~ m/ a.c / {
    say "Match";
}
if 'ac' ~~ m/ a.c / {
    say "Match";
  } else {
    say "No Match";
}
----

=== Quantifiers
Quantifiers come after a character and are used to specify how many times we are expecting it.

The question mark `?` means zero or one time.

[source,perl6]
----
if 'ac' ~~ m/ a?c / {
    say "Match";
  } else {
    say "No Match";
}
if 'c' ~~ m/ a?c / {
    say "Match";
  } else {
    say "No Match";
}
----

The star `*` means zero or multiple times.

[source,perl6]
----
if 'az' ~~ m/ a*z / {
    say "Match";
  } else {
    say "No Match";
}
if 'aaz' ~~ m/ a*z / {
    say "Match";
  } else {
    say "No Match";
}
if 'aaaaaaaaaaz' ~~ m/ a*z / {
    say "Match";
  } else {
    say "No Match";
}
if 'z' ~~ m/ a*z / {
    say "Match";
  } else {
    say "No Match";
}
----

The `+` means at least one time.

[source,perl6]
----
if 'az' ~~ m/ a+z / {
    say "Match";
  } else {
    say "No Match";
}
if 'aaz' ~~ m/ a+z / {
    say "Match";
  } else {
    say "No Match";
}
if 'aaaaaaaaaaz' ~~ m/ a+z / {
    say "Match";
  } else {
    say "No Match";
}
if 'z' ~~ m/ a+z / {
    say "Match";
  } else {
    say "No Match";
}
----

=== Match Results
Whenever the process of matching a string against a regex is successful,
the match result is stored in a special variable `$/`

[source,perl6]
.Script
----
if 'Rakudo is a Perl 6 compiler' ~~ m/:s Perl 6/ {
    say "The match is: " ~ $/;
    say "The string before the match is: " ~ $/.prematch;
    say "The string after the match is: " ~ $/.postmatch;
    say "The matching string starts at position: " ~ $/.from;
    say "The matching string ends at position: " ~ $/.to;
}
----

.Output
----
The match is: Perl 6
The string before the match is: Rakudo is a
The string after the match is:  compiler
The matching string starts at position: 12
The matching string ends at position: 18
----

.Explanation
`$/` returns a _Match Object_ (the string that matches the regex) +
The following methods can be called on the _Match Object_: +
`.prematch` returns the string preceding the match. +
`.postmatch` returns the string following the match. +
`.from` returns the starting position of the match. +
`.to` returns the ending position of the match. +

TIP: By default whitespace in a regex definition is irrelevant. +
If we want to match against a regex containing whitespace we have to do so explicitly. +
The `:s` in the regex `m/:s Perl 6/` forces whitespace to be considered and not discarded. +
Alternatively we could have written the regex as `m/ Perl\s6 /` and used `\s` which as we saw earlier is a placeholder for whitespace. +
If a regex contains more than a single whitespace, using `:s` becomes more effective in contrast with using `\s` for each and every whitespace.

=== Example
Lets check if an email is valid or not. +
For the sake of this example we will assume that a valid email address is formed as following: +
first name [dot] last name [at] company [dot] (com/org/net)

WARNING: The regex used in this example for email validation is not very accurate. +
Its sole purpose is to demonstrate regex functionality in Perl 6. +
Do not use it as-is in production.

[source,perl6]
.Script
----
my $email = 'john.doe@perl6.org';
my $regex = / <:L>+\.<:L>+\@<:L+:N>+\.<:L>+ /;

if $email ~~ $regex {
  say $/ ~ " is a valid email";
} else {
  say "This is not a valid email";
}
----

.Output
`john.doe@perl6.org is a valid email`

.Explanation
`<:L>` matches a single letter +
`<:L>+` matches a single letter or more +
`\.` matches a single [dot] character +
`\@` matches a single [at] character +
`<:L+:N>` matches a letter and a number +
`<:L+:N>+` matches one or more (letters and numbers) +

The regex can be decomposed as following:

* *first name* `<:L>+`

* *[dot]* `\.`

* *last name* `<:L>+`

* *[at]* `\@`

* *company name* `<:L+:N>+`

* *[dot]* `\.`

* *com/org/net* `<:L>+`

[source,perl6]
.Alternatively a regex can be broken down into multiple named regexes
----
my $email = 'john.doe@perl6.org';
my regex many-letters { <:L>+ };
my regex dot { \. };
my regex at { \@ };
my regex many-letters-numbers { <:L+:N>+ };

if $email ~~ / <many-letters> <dot> <many-letters> <at> <many-letters-numbers> <dot> <many-letters> / {
  say $/ ~ " is a valid email";
} else {
  say "This is not a valid email";
}
----

A named regex is defined using the following syntax: `my regex regex-name { regex definition }` +
A named regex can be called using the following syntax: `<regex-name>`

NOTE: For more info on regexes, see https://docs.perl6.org/language/regexes

== Perl 6 Modules
Perl 6 is a general purpose programming language. It can be used to tackle a multitude of tasks including:
text manipulation, graphics, web, databases, network protocols etc.

Reusability is a very important concept whereby programmers don't have to reinvent the wheel each time they want to do a new task.

Perl 6 allows the creation and redistribution of *modules*. Each module is a packaged set of functionality that can be reused once installed.

_Panda_ is a module management tool that comes with Rakudo Star.

To install a specific module, type the below command in your terminal:

`panda install "module name"`

NOTE: The Perl 6 modules directory can be found on: https://modules.perl6.org/

=== Using Modules
MD5 is a cryptographic hash function that produces a 128-bit hash value. +
MD5 has a variety of applications of which encryption of passwords stored in a database.
When a new user registers, their credentials are not stored as plain text but rather _hashed_.
The rationale behind this is that if the DB gets compromised, the attacker will not be able to know what the passwords are.

Lets say you need a script that generates the MD5 hash of a password in preparation for storing it in the DB.

Luckily there's a Perl 6 module that already implemented the MD5 algorithm. Lets install it: +
`panda install Digest::MD5`

Now run the below script:
[source,perl6]
----
use Digest::MD5;
my $password = "password123";
my $hashed-password = Digest::MD5.new.md5_hex($password);

say $hashed-password;
----
In order to run the `md5_hex()` function that creates hashes, we need to load the required module. +
The `use` keyword loads the module for use in the script.

WARNING: In practice MD5 hashing alone is not sufficient, because it is prone to dictionary attacks. +
It should be combined with a salt link:https://en.wikipedia.org/wiki/Salt_(cryptography)[https://en.wikipedia.org/wiki/Salt_(cryptography)].

== Unicode

Unicode is a standard for encoding and representing text, that caters for most writing systems in the world. +
UTF-8 is a character encoding capable of encoding all possible characters, or code points, in Unicode.

Characters are defined by a: +
*Grapheme*: Visual representation. +
*Code point*: A number assigned to the character.

=== Using Unicode

.Lets look at how we can output characters using Unicode
[source,perl6]
----
say "a";
say "\x0061";
say "\c[LATIN SMALL LETTER A]";
----
The above 3 lines showcase different ways of building a character:

. Writing the character directly (grapheme)

. Using `\x` and the code point

. Using `\c` and the code point name

.Now lets output a smiley
[source,perl6]
----
say "☺";
say "\x263a";
say "\c[WHITE SMILING FACE]";
----

.Another example combining two code points
[source,perl6]
----
say "á";
say "\x00e1";
say "\x0061\x0301";
say "\c[LATIN SMALL LETTER A WITH ACUTE]";
----

The letter `á` can be written:

* using its unique code point `\x00e1`

* or as a combination of the code points of `a` and acute `\x0061\x0301`

.Some of the methods that can be used:
[source,perl6]
----
say "á".NFC;
say "á".NFD;
say "á".uniname;
----

.`Output`
----
NFC:0x<00e1>
NFD:0x<0061 0301>
LATIN SMALL LETTER A WITH ACUTE
----

`NFC` returns the unique code point. +
`NFD` decomposes the character and return the code point of each part. +
`uniname` returns the code point name.

.Unicode letters can be used as identifiers:
[source,perl6]
----
my $Δ = 1;
$Δ++;
say $Δ;
----

.Unicode can be used to do math:
[source,perl6]
----
my $var = 2 + ⅒;
say $var;
----

== Parallelism, Concurrency and Asynchrony

=== Parallelism
Under normal circumstances, all tasks in a program run sequentially. +
This might not be a problem unless what you're trying to do is consuming a lot of time.

Naturally speaking Perl 6 has features that will enable you to run things in parallel. +
At this stage, it is important to note that parallelism can mean one of two things:

* *Task Parallelism*: Two (or more) independent expressions running in parallel.

* *Data Parallelism*: A single expression iterating over a list of elements in parallel.

Lets begin with the latter.

==== Data Parallelism
[source,perl6]
----
my @array = (0..50000);                     #Array population
my @result = @array.map({ is-prime $_ });   #call is-prime for each array element
say now - INIT now;                         #Output the time it took for the script to complete
----

.Considering the above example:
We are only doing one operation `@array.map({ is-prime $_ })` +
The `is-prime` subroutine is being called for each array element sequentially: +
`is-prime @array[0]` then `is-prime @array[1]` then `is-prime @array[2]` etc.

.Fortunately we can call `is-prime` on multiple array elements at the same time:
[source,perl6]
----
my @array = (0..50000);                         #Array population
my @result = @array.race.map({ is-prime $_ });  #call is-prime for each array element
say now - INIT now;                             #Output the time it took to complete
----

Notice the use of `race` in the expression.
This method will enable parallel iteration of the array elements.

After running both examples (with and without `race`), compare the time it took for both scripts to complete.

[TIP]
====
`race` will not preserve the order of elements. If you wish to do, so use `hyper` instead.

[source,perl6]
.race
----
my @array = (1..1000);
my @result = @array.race.map( {$_ + 1} );
@result>>.say;
----

[source,perl6]
.hyper
----
my @array = (1..1000);
my @result = @array.hyper.map( {$_ + 1} );
@result>>.say;
----

If you run both examples, you should notice that one is sorted and the other is not.

====

==== Task Parallelism

[source,perl6]
----
my @array1 = (0..49999);
my @array2 = (2..50001);

my @result1 = @array1.map( {is-prime($_ + 1)} );
my @result2 = @array2.map( {is-prime($_ - 1)} );

say @result1 eqv @result2;

say now - INIT now;
----

.Considering the above example:

. We defined 2 arrays

. applied a different operation for each array and stored the results

. and checked if both results are the same

The script waits for `@array1.map( {is-prime($_ + 1)} )` to finish +
and then evaluates `@array2.map( {is-prime($_ - 1)} )`

Both operations applied to each array do not depend on each other.

.Why not do both in parallel?
[source,perl6]
----
my @array1 = (0..49999);
my @array2 = (2..50001);

my $promise1 = start @array1.map( {is-prime($_ + 1)} ).eager;
my $promise2 = start @array2.map( {is-prime($_ - 1)} ).eager;

my @result1 = await $promise1;
my @result2 = await $promise2;

say @result1 eqv @result2;

say now - INIT now;
----

.Explanation
The `start` method evaluates the code and returns *an object of type promise* or shortly *a promise*. +
If the code is evaluated correctly, the _promise_ will be *kept*. +
If the code throws an exception, the _promise_ will be *broken*.

The `await` method waits for a *promise*. +
If it's *kept* it will get the returned values. +
If it's *broken* it will get the exception thrown.

Check the time it took each script to complete.

WARNING: Parallelism always adds a threading overhead. If that overhead is not offset by gains in computational speed, the script will seem slower. +
This is why, using `race`, `hyper`, `start` and `await` for fairly simple scripts can actually slow them down.

=== Concurrency and Asynchrony
NOTE: For more info on Concurrency and Asynchronous Programming, see https://docs.perl6.org/language/concurrency

== The Community

* link:irc://irc.freenode.net/#perl6[#perl6] IRC channel. Much discussion happens on IRC. This should be your go to place for any enquiry: https://perl6.org/community/irc

* link:http://pl6anet.org[pl6anet] blog aggregator. Stay tuned by reading blog posts that focus on Perl 6.

* link:https://www.reddit.com/r/perl6/[/r/perl6] Subscribe to the Perl 6 subreddit.
